[package]
name = "ddk_ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "ddk_ffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
uniffi = { version = "0.29.4", features = ["cli"] }
dlc = { path = "../../../ernest/dlcdevkit/dlc", features = ["use-serde"] }

[build-dependencies]
uniffi = { version = "0.29.4", features = ["build"] }

[package.metadata.uniffi]
udl_file = "src/ddk_ffi.udl"

[[bin]]
name = "uniffi-bindgen"
path = "src/uniffi-bindgen.rs"
