[package]
name = "ddk_ffi"
version = "0.4.0"
edition = "2021"
license = "MIT"
description = "rust-dlc language bindings"
repository = "https://github.com/bennyhodl/ddk-ffi"
homepage = "https://github.com/bennyhodl/ddk-ffi"
readme = "README.md"

[lib]
name = "ddk_ffi"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
uniffi = { version = "=0.31.0", features = ["cli"] }
ddk = { version = "2.0.0-rc.1", default-features = false }
ddk-dlc = { version = "2.0.0-rc.1", features = ["std", "use-serde"] }
ddk-messages = { version = "2.0.0-rc.1", features = ["std", "use-serde"] }
lightning = { version = "0.2", features = ["std"] }
bitcoin = "0.32.7"
thiserror = "2.0.12"
secp256k1-zkp = "0.11.0"
bip39 = "2.2.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
uniffi = { version = "=0.31.0", features = ["cli", "wasm-unstable-single-threaded"] }

[dev-dependencies]
bip39 = {version = "2.2.0", features = ["rand"]}

[[bin]]
name = "uniffi-bindgen"
path = "src/uniffi-bindgen.rs"
