// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck

import lib from '@ubjs/node'
const { UniffiNativeModule, FfiType, resolveLibPath } = lib

import {
  type StructuralEquality as UniffiStructuralEquality,
  type UniffiForeignFuture as RuntimeUniffiForeignFuture,
  type UniffiRustCallStatus,
  type UniffiGcObject,
  type UniffiRustFutureContinuationCallback as RuntimeUniffiRustFutureContinuationCallback,
  type UniffiResult,
} from '@ubjs/core'

const DEFINITIONS = {
  symbols: {
    rustbuffer_alloc: 'ffi_ddk_ffi_rustbuffer_alloc',
    rustbuffer_free: 'ffi_ddk_ffi_rustbuffer_free',
    rustbuffer_from_bytes: 'ffi_ddk_ffi_rustbuffer_from_bytes',
  },
  functions: {
    ffi_ddk_ffi_rust_future_poll_u8: {
      args: [FfiType.Handle, FfiType.Callback('RustFutureContinuationCallback'), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_cancel_u8: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_complete_u8: {
      args: [FfiType.Handle],
      ret: FfiType.UInt8,
      hasRustCallStatus: true,
    },
    ffi_ddk_ffi_rust_future_free_u8: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_poll_i8: {
      args: [FfiType.Handle, FfiType.Callback('RustFutureContinuationCallback'), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_cancel_i8: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_complete_i8: {
      args: [FfiType.Handle],
      ret: FfiType.Int8,
      hasRustCallStatus: true,
    },
    ffi_ddk_ffi_rust_future_free_i8: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_poll_u16: {
      args: [FfiType.Handle, FfiType.Callback('RustFutureContinuationCallback'), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_cancel_u16: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_complete_u16: {
      args: [FfiType.Handle],
      ret: FfiType.UInt16,
      hasRustCallStatus: true,
    },
    ffi_ddk_ffi_rust_future_free_u16: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_poll_i16: {
      args: [FfiType.Handle, FfiType.Callback('RustFutureContinuationCallback'), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_cancel_i16: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_complete_i16: {
      args: [FfiType.Handle],
      ret: FfiType.Int16,
      hasRustCallStatus: true,
    },
    ffi_ddk_ffi_rust_future_free_i16: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_poll_u32: {
      args: [FfiType.Handle, FfiType.Callback('RustFutureContinuationCallback'), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_cancel_u32: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_complete_u32: {
      args: [FfiType.Handle],
      ret: FfiType.UInt32,
      hasRustCallStatus: true,
    },
    ffi_ddk_ffi_rust_future_free_u32: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_poll_i32: {
      args: [FfiType.Handle, FfiType.Callback('RustFutureContinuationCallback'), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_cancel_i32: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_complete_i32: {
      args: [FfiType.Handle],
      ret: FfiType.Int32,
      hasRustCallStatus: true,
    },
    ffi_ddk_ffi_rust_future_free_i32: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_poll_u64: {
      args: [FfiType.Handle, FfiType.Callback('RustFutureContinuationCallback'), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_cancel_u64: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_complete_u64: {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    ffi_ddk_ffi_rust_future_free_u64: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_poll_i64: {
      args: [FfiType.Handle, FfiType.Callback('RustFutureContinuationCallback'), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_cancel_i64: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_complete_i64: {
      args: [FfiType.Handle],
      ret: FfiType.Int64,
      hasRustCallStatus: true,
    },
    ffi_ddk_ffi_rust_future_free_i64: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_poll_f32: {
      args: [FfiType.Handle, FfiType.Callback('RustFutureContinuationCallback'), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_cancel_f32: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_complete_f32: {
      args: [FfiType.Handle],
      ret: FfiType.Float32,
      hasRustCallStatus: true,
    },
    ffi_ddk_ffi_rust_future_free_f32: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_poll_f64: {
      args: [FfiType.Handle, FfiType.Callback('RustFutureContinuationCallback'), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_cancel_f64: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_complete_f64: {
      args: [FfiType.Handle],
      ret: FfiType.Float64,
      hasRustCallStatus: true,
    },
    ffi_ddk_ffi_rust_future_free_f64: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_poll_rust_buffer: {
      args: [FfiType.Handle, FfiType.Callback('RustFutureContinuationCallback'), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_cancel_rust_buffer: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_complete_rust_buffer: {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    ffi_ddk_ffi_rust_future_free_rust_buffer: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_poll_void: {
      args: [FfiType.Handle, FfiType.Callback('RustFutureContinuationCallback'), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_cancel_void: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ffi_ddk_ffi_rust_future_complete_void: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    ffi_ddk_ffi_rust_future_free_void: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_fn_clone_contractkeyprovider: {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_free_contractkeyprovider: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_accept_offer: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_chain_hash_from_network: {
      args: [FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_compute_contract_id: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_contract_info_payouts: {
      args: [FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_convert_mnemonic_to_seed: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_cet: {
      args: [
        FfiType.RustBuffer,
        FfiType.UInt64,
        FfiType.RustBuffer,
        FfiType.UInt64,
        FfiType.RustBuffer,
        FfiType.UInt32,
        FfiType.UInt32,
      ],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_cet_adaptor_points_from_oracle_info: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_cet_adaptor_sigs_from_oracle_info: {
      args: [
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.UInt64,
        FfiType.RustBuffer,
      ],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_cet_adaptor_sigs_from_points: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.UInt64],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_cets: {
      args: [
        FfiType.RustBuffer,
        FfiType.UInt32,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.UInt32,
        FfiType.UInt64,
        FfiType.UInt64,
      ],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_dlc_splice_input: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.UInt16],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_dlc_transactions: {
      args: [
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.UInt32,
        FfiType.UInt64,
        FfiType.UInt32,
        FfiType.UInt32,
        FfiType.UInt64,
        FfiType.UInt8,
      ],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_extkey_from_parent_path: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_extkey_from_seed: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_fund_tx_locking_script: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_funding_psbt: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_offer: {
      args: [FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_refund_transaction: {
      args: [
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.UInt64,
        FfiType.UInt64,
        FfiType.UInt32,
        FfiType.RustBuffer,
        FfiType.UInt32,
      ],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_spliced_dlc_transactions: {
      args: [
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.UInt32,
        FfiType.UInt64,
        FfiType.UInt32,
        FfiType.UInt32,
        FfiType.UInt64,
        FfiType.UInt8,
      ],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_create_xpriv_from_parent_path: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_dlc_input_max_witness_len: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_dlc_transactions_from_messages: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_extract_ecdsa_signature_from_oracle_signatures: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_finalize_sign: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_finalize_sign_spliced: {
      args: [
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.Handle,
        FfiType.RustBuffer,
      ],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_funding_input: {
      args: [
        FfiType.RustBuffer,
        FfiType.UInt32,
        FfiType.RustBuffer,
        FfiType.UInt32,
        FfiType.UInt16,
        FfiType.RustBuffer,
      ],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_get_pubkey_from_extkey: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_get_total_input_vsize: {
      args: [FfiType.RustBuffer],
      ret: FfiType.UInt32,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_get_xpub_from_xpriv: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_sign_accept: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_sign_accept_spliced: {
      args: [
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.Handle,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
      ],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_sign_contract_cet: {
      args: [
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.Handle,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
      ],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_sign_contract_refund: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_sign_funding_psbt_with_descriptor: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_validate_accept: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_validate_offer: {
      args: [FfiType.RustBuffer, FfiType.UInt32, FfiType.UInt32],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_validate_sign: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_verify_cet_adaptor_sigs_from_oracle_info: {
      args: [
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.UInt64,
        FfiType.RustBuffer,
      ],
      ret: FfiType.Int8,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_func_version: {
      args: [],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_method_adaptorsignature_verify_from_oracle_info: {
      args: [
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.UInt64,
        FfiType.RustBuffer,
      ],
      ret: FfiType.Int8,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_method_partyparams_change_output_and_fees: {
      args: [FfiType.RustBuffer, FfiType.UInt64],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_method_transaction_add_signature: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.UInt32],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_method_transaction_cet_adaptor_signature_from_oracle_info: {
      args: [
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.UInt64,
        FfiType.RustBuffer,
      ],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_method_transaction_cet_adaptor_signature_inputs: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.UInt64, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_method_transaction_cet_sighash: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.UInt64],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_method_transaction_raw_funding_input_signature: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.UInt32, FfiType.UInt64],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_method_transaction_sign_cet: {
      args: [
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.UInt64,
      ],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_method_transaction_sign_fund_input: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.UInt32, FfiType.UInt64],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_method_transaction_sign_multi_sig_input: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_method_transaction_verify_fund_signature: {
      args: [
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.RustBuffer,
        FfiType.UInt32,
        FfiType.UInt64,
      ],
      ret: FfiType.Int8,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_method_txoutput_is_dust: {
      args: [FfiType.RustBuffer],
      ret: FfiType.Int8,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_constructor_contractkeyprovider_from_descriptor: {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_constructor_contractkeyprovider_from_mnemonic: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_constructor_contractkeyprovider_from_seed: {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_constructor_contractkeyprovider_from_xprv: {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    uniffi_ddk_ffi_fn_method_contractkeyprovider_funding_pubkey: {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    ffi_ddk_ffi_uniffi_contract_version: {
      args: [],
      ret: FfiType.UInt32,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_accept_offer: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_chain_hash_from_network: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_compute_contract_id: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_contract_info_payouts: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_convert_mnemonic_to_seed: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_cet: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_cet_adaptor_points_from_oracle_info: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_cet_adaptor_sigs_from_oracle_info: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_cet_adaptor_sigs_from_points: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_cets: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_dlc_splice_input: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_dlc_transactions: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_extkey_from_parent_path: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_extkey_from_seed: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_fund_tx_locking_script: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_funding_psbt: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_offer: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_refund_transaction: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_spliced_dlc_transactions: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_create_xpriv_from_parent_path: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_dlc_input_max_witness_len: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_dlc_transactions_from_messages: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_extract_ecdsa_signature_from_oracle_signatures: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_finalize_sign: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_finalize_sign_spliced: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_funding_input: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_get_pubkey_from_extkey: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_get_total_input_vsize: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_get_xpub_from_xpriv: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_sign_accept: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_sign_accept_spliced: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_sign_contract_cet: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_sign_contract_refund: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_sign_funding_psbt_with_descriptor: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_validate_accept: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_validate_offer: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_validate_sign: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_verify_cet_adaptor_sigs_from_oracle_info: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_func_version: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_constructor_contractkeyprovider_from_descriptor: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_constructor_contractkeyprovider_from_mnemonic: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_constructor_contractkeyprovider_from_seed: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_constructor_contractkeyprovider_from_xprv: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    uniffi_ddk_ffi_checksum_method_contractkeyprovider_funding_pubkey: {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
  },
  callbacks: {
    RustFutureContinuationCallback: {
      args: [FfiType.Handle, FfiType.Int8],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    ForeignFutureDroppedCallback: {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
  },
  structs: {
    ForeignFutureDroppedCallbackStruct: [
      { name: 'handle', type: FfiType.Handle },
      { name: 'free', type: FfiType.Callback('ForeignFutureDroppedCallback') },
    ],
  },
} as const

interface NativeModuleInterface {
  ffi_ddk_ffi_rust_future_poll_u8(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint,
  ): void
  ffi_ddk_ffi_rust_future_cancel_u8(handle: bigint): void
  ffi_ddk_ffi_rust_future_complete_u8(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number
  ffi_ddk_ffi_rust_future_free_u8(handle: bigint): void
  ffi_ddk_ffi_rust_future_poll_i8(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint,
  ): void
  ffi_ddk_ffi_rust_future_cancel_i8(handle: bigint): void
  ffi_ddk_ffi_rust_future_complete_i8(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number
  ffi_ddk_ffi_rust_future_free_i8(handle: bigint): void
  ffi_ddk_ffi_rust_future_poll_u16(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint,
  ): void
  ffi_ddk_ffi_rust_future_cancel_u16(handle: bigint): void
  ffi_ddk_ffi_rust_future_complete_u16(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number
  ffi_ddk_ffi_rust_future_free_u16(handle: bigint): void
  ffi_ddk_ffi_rust_future_poll_i16(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint,
  ): void
  ffi_ddk_ffi_rust_future_cancel_i16(handle: bigint): void
  ffi_ddk_ffi_rust_future_complete_i16(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number
  ffi_ddk_ffi_rust_future_free_i16(handle: bigint): void
  ffi_ddk_ffi_rust_future_poll_u32(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint,
  ): void
  ffi_ddk_ffi_rust_future_cancel_u32(handle: bigint): void
  ffi_ddk_ffi_rust_future_complete_u32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number
  ffi_ddk_ffi_rust_future_free_u32(handle: bigint): void
  ffi_ddk_ffi_rust_future_poll_i32(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint,
  ): void
  ffi_ddk_ffi_rust_future_cancel_i32(handle: bigint): void
  ffi_ddk_ffi_rust_future_complete_i32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number
  ffi_ddk_ffi_rust_future_free_i32(handle: bigint): void
  ffi_ddk_ffi_rust_future_poll_u64(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint,
  ): void
  ffi_ddk_ffi_rust_future_cancel_u64(handle: bigint): void
  ffi_ddk_ffi_rust_future_complete_u64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): bigint
  ffi_ddk_ffi_rust_future_free_u64(handle: bigint): void
  ffi_ddk_ffi_rust_future_poll_i64(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint,
  ): void
  ffi_ddk_ffi_rust_future_cancel_i64(handle: bigint): void
  ffi_ddk_ffi_rust_future_complete_i64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): bigint
  ffi_ddk_ffi_rust_future_free_i64(handle: bigint): void
  ffi_ddk_ffi_rust_future_poll_f32(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint,
  ): void
  ffi_ddk_ffi_rust_future_cancel_f32(handle: bigint): void
  ffi_ddk_ffi_rust_future_complete_f32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number
  ffi_ddk_ffi_rust_future_free_f32(handle: bigint): void
  ffi_ddk_ffi_rust_future_poll_f64(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint,
  ): void
  ffi_ddk_ffi_rust_future_cancel_f64(handle: bigint): void
  ffi_ddk_ffi_rust_future_complete_f64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number
  ffi_ddk_ffi_rust_future_free_f64(handle: bigint): void
  ffi_ddk_ffi_rust_future_poll_rust_buffer(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint,
  ): void
  ffi_ddk_ffi_rust_future_cancel_rust_buffer(handle: bigint): void
  ffi_ddk_ffi_rust_future_complete_rust_buffer(handle: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array
  ffi_ddk_ffi_rust_future_free_rust_buffer(handle: bigint): void
  ffi_ddk_ffi_rust_future_poll_void(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint,
  ): void
  ffi_ddk_ffi_rust_future_cancel_void(handle: bigint): void
  ffi_ddk_ffi_rust_future_complete_void(handle: bigint, uniffi_out_err: UniffiRustCallStatus): void
  ffi_ddk_ffi_rust_future_free_void(handle: bigint): void
  uniffi_ddk_ffi_fn_clone_contractkeyprovider(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint
  uniffi_ddk_ffi_fn_free_contractkeyprovider(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void
  uniffi_ddk_ffi_fn_func_accept_offer(
    offer: Uint8Array,
    params: Uint8Array,
    keys: bigint,
    newTemporaryContractId: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_chain_hash_from_network(network: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array
  uniffi_ddk_ffi_fn_func_compute_contract_id(
    offer: Uint8Array,
    accept: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_contract_info_payouts(
    contractInfo: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_convert_mnemonic_to_seed(
    mnemonic: Uint8Array,
    passphrase: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_create_cet(
    localOutput: Uint8Array,
    localPayoutSerialId: bigint,
    remoteOutput: Uint8Array,
    remotePayoutSerialId: bigint,
    fundTxId: Uint8Array,
    fundVout: number,
    lockTime: number,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_create_cet_adaptor_points_from_oracle_info(
    oracleInfo: Uint8Array,
    msgs: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_create_cet_adaptor_sigs_from_oracle_info(
    cets: Uint8Array,
    oracleInfo: Uint8Array,
    fundingSecretKey: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    fundOutputValue: bigint,
    msgs: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_create_cet_adaptor_sigs_from_points(
    cets: Uint8Array,
    adaptorPoints: Uint8Array,
    fundingSecretKey: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    fundOutputValue: bigint,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_create_cets(
    fundTxId: Uint8Array,
    fundVout: number,
    localFinalScriptPubkey: Uint8Array,
    remoteFinalScriptPubkey: Uint8Array,
    outcomes: Uint8Array,
    lockTime: number,
    localSerialId: bigint,
    remoteSerialId: bigint,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_create_dlc_splice_input(
    prevOffer: Uint8Array,
    prevAccept: Uint8Array,
    localParty: Uint8Array,
    inputSerialId: Uint8Array,
    maxWitnessLen: number,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_create_dlc_transactions(
    outcomes: Uint8Array,
    localParams: Uint8Array,
    remoteParams: Uint8Array,
    refundLocktime: number,
    feeRate: bigint,
    fundLockTime: number,
    cetLockTime: number,
    fundOutputSerialId: bigint,
    contractFlags: number,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_create_extkey_from_parent_path(
    extkey: Uint8Array,
    path: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_create_extkey_from_seed(
    seed: Uint8Array,
    network: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_create_fund_tx_locking_script(
    localFundPubkey: Uint8Array,
    remoteFundPubkey: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_create_funding_psbt(
    offer: Uint8Array,
    accept: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_create_offer(params: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array
  uniffi_ddk_ffi_fn_func_create_refund_transaction(
    localFinalScriptPubkey: Uint8Array,
    remoteFinalScriptPubkey: Uint8Array,
    localAmount: bigint,
    remoteAmount: bigint,
    lockTime: number,
    fundTxId: Uint8Array,
    fundVout: number,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_create_spliced_dlc_transactions(
    outcomes: Uint8Array,
    localParams: Uint8Array,
    remoteParams: Uint8Array,
    refundLocktime: number,
    feeRate: bigint,
    fundLockTime: number,
    cetLockTime: number,
    fundOutputSerialId: bigint,
    contractFlags: number,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_create_xpriv_from_parent_path(
    seedOrXpriv: Uint8Array,
    baseDerivationPath: Uint8Array,
    network: Uint8Array,
    path: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_dlc_input_max_witness_len(uniffi_out_err: UniffiRustCallStatus): number
  uniffi_ddk_ffi_fn_func_dlc_transactions_from_messages(
    offer: Uint8Array,
    accept: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_extract_ecdsa_signature_from_oracle_signatures(
    oracleSignatures: Uint8Array,
    adaptorSignature: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_finalize_sign(
    offer: Uint8Array,
    accept: Uint8Array,
    sign: Uint8Array,
    signedFundingPsbt: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_finalize_sign_spliced(
    offer: Uint8Array,
    accept: Uint8Array,
    sign: Uint8Array,
    signedFundingPsbt: Uint8Array,
    keys: bigint,
    spliceKeys: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_funding_input(
    previousTransaction: Uint8Array,
    vout: number,
    inputSerialId: Uint8Array,
    sequence: number,
    maxWitnessLen: number,
    redeemScript: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_get_pubkey_from_extkey(
    extkey: Uint8Array,
    network: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_get_total_input_vsize(inputs: Uint8Array, uniffi_out_err: UniffiRustCallStatus): number
  uniffi_ddk_ffi_fn_func_get_xpub_from_xpriv(
    xpriv: Uint8Array,
    network: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_sign_accept(
    offer: Uint8Array,
    accept: Uint8Array,
    keys: bigint,
    temporaryContractId: Uint8Array,
    signedFundingPsbt: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_sign_accept_spliced(
    offer: Uint8Array,
    accept: Uint8Array,
    keys: bigint,
    temporaryContractId: Uint8Array,
    signedFundingPsbt: Uint8Array,
    spliceKeys: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_sign_contract_cet(
    offer: Uint8Array,
    accept: Uint8Array,
    sign: Uint8Array,
    keys: bigint,
    temporaryContractId: Uint8Array,
    attestations: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_sign_contract_refund(
    offer: Uint8Array,
    accept: Uint8Array,
    sign: Uint8Array,
    keys: bigint,
    temporaryContractId: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_sign_funding_psbt_with_descriptor(
    offer: Uint8Array,
    accept: Uint8Array,
    fundingPsbt: Uint8Array,
    descriptor: Uint8Array,
    inputs: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_func_validate_accept(
    offer: Uint8Array,
    accept: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): void
  uniffi_ddk_ffi_fn_func_validate_offer(
    offer: Uint8Array,
    minTimeoutInterval: number,
    maxTimeoutInterval: number,
    uniffi_out_err: UniffiRustCallStatus,
  ): void
  uniffi_ddk_ffi_fn_func_validate_sign(
    offer: Uint8Array,
    accept: Uint8Array,
    sign: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): void
  uniffi_ddk_ffi_fn_func_verify_cet_adaptor_sigs_from_oracle_info(
    adaptorSigs: Uint8Array,
    cets: Uint8Array,
    oracleInfos: Uint8Array,
    pubkey: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    totalCollateral: bigint,
    msgs: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): number
  uniffi_ddk_ffi_fn_func_version(uniffi_out_err: UniffiRustCallStatus): Uint8Array
  uniffi_ddk_ffi_fn_method_adaptorsignature_verify_from_oracle_info(
    uniffiSelf: Uint8Array,
    cet: Uint8Array,
    oracleInfos: Uint8Array,
    pubkey: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    totalCollateral: bigint,
    msgs: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): number
  uniffi_ddk_ffi_fn_method_partyparams_change_output_and_fees(
    uniffiSelf: Uint8Array,
    feeRate: bigint,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_method_transaction_add_signature(
    uniffiSelf: Uint8Array,
    signature: Uint8Array,
    pubkey: Uint8Array,
    inputIndex: number,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_method_transaction_cet_adaptor_signature_from_oracle_info(
    uniffiSelf: Uint8Array,
    oracleInfo: Uint8Array,
    fundingSk: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    totalCollateral: bigint,
    msgs: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_method_transaction_cet_adaptor_signature_inputs(
    uniffiSelf: Uint8Array,
    oracleInfo: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    fundOutputValue: bigint,
    msgs: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_method_transaction_cet_sighash(
    uniffiSelf: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    fundOutputValue: bigint,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_method_transaction_raw_funding_input_signature(
    uniffiSelf: Uint8Array,
    privkey: Uint8Array,
    prevTxId: Uint8Array,
    prevTxVout: number,
    value: bigint,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_method_transaction_sign_cet(
    uniffiSelf: Uint8Array,
    adaptorSignature: Uint8Array,
    oracleSignatures: Uint8Array,
    fundingSecretKey: Uint8Array,
    otherPubkey: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    fundOutputValue: bigint,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_method_transaction_sign_fund_input(
    uniffiSelf: Uint8Array,
    privkey: Uint8Array,
    prevTxId: Uint8Array,
    prevTxVout: number,
    value: bigint,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_method_transaction_sign_multi_sig_input(
    uniffiSelf: Uint8Array,
    dlcInput: Uint8Array,
    localPrivkey: Uint8Array,
    remoteSignature: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  uniffi_ddk_ffi_fn_method_transaction_verify_fund_signature(
    uniffiSelf: Uint8Array,
    signature: Uint8Array,
    pubkey: Uint8Array,
    txid: Uint8Array,
    vout: number,
    inputAmount: bigint,
    uniffi_out_err: UniffiRustCallStatus,
  ): number
  uniffi_ddk_ffi_fn_method_txoutput_is_dust(uniffiSelf: Uint8Array, uniffi_out_err: UniffiRustCallStatus): number
  uniffi_ddk_ffi_fn_constructor_contractkeyprovider_from_descriptor(
    descriptor: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): bigint
  uniffi_ddk_ffi_fn_constructor_contractkeyprovider_from_mnemonic(
    mnemonic: Uint8Array,
    passphrase: Uint8Array,
    network: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): bigint
  uniffi_ddk_ffi_fn_constructor_contractkeyprovider_from_seed(
    seed: Uint8Array,
    network: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): bigint
  uniffi_ddk_ffi_fn_constructor_contractkeyprovider_from_xprv(
    xprv: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): bigint
  uniffi_ddk_ffi_fn_method_contractkeyprovider_funding_pubkey(
    uniffiSelf: bigint,
    temporaryContractId: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus,
  ): Uint8Array
  ffi_ddk_ffi_uniffi_contract_version(): number
  uniffi_ddk_ffi_checksum_func_accept_offer(): number
  uniffi_ddk_ffi_checksum_func_chain_hash_from_network(): number
  uniffi_ddk_ffi_checksum_func_compute_contract_id(): number
  uniffi_ddk_ffi_checksum_func_contract_info_payouts(): number
  uniffi_ddk_ffi_checksum_func_convert_mnemonic_to_seed(): number
  uniffi_ddk_ffi_checksum_func_create_cet(): number
  uniffi_ddk_ffi_checksum_func_create_cet_adaptor_points_from_oracle_info(): number
  uniffi_ddk_ffi_checksum_func_create_cet_adaptor_sigs_from_oracle_info(): number
  uniffi_ddk_ffi_checksum_func_create_cet_adaptor_sigs_from_points(): number
  uniffi_ddk_ffi_checksum_func_create_cets(): number
  uniffi_ddk_ffi_checksum_func_create_dlc_splice_input(): number
  uniffi_ddk_ffi_checksum_func_create_dlc_transactions(): number
  uniffi_ddk_ffi_checksum_func_create_extkey_from_parent_path(): number
  uniffi_ddk_ffi_checksum_func_create_extkey_from_seed(): number
  uniffi_ddk_ffi_checksum_func_create_fund_tx_locking_script(): number
  uniffi_ddk_ffi_checksum_func_create_funding_psbt(): number
  uniffi_ddk_ffi_checksum_func_create_offer(): number
  uniffi_ddk_ffi_checksum_func_create_refund_transaction(): number
  uniffi_ddk_ffi_checksum_func_create_spliced_dlc_transactions(): number
  uniffi_ddk_ffi_checksum_func_create_xpriv_from_parent_path(): number
  uniffi_ddk_ffi_checksum_func_dlc_input_max_witness_len(): number
  uniffi_ddk_ffi_checksum_func_dlc_transactions_from_messages(): number
  uniffi_ddk_ffi_checksum_func_extract_ecdsa_signature_from_oracle_signatures(): number
  uniffi_ddk_ffi_checksum_func_finalize_sign(): number
  uniffi_ddk_ffi_checksum_func_finalize_sign_spliced(): number
  uniffi_ddk_ffi_checksum_func_funding_input(): number
  uniffi_ddk_ffi_checksum_func_get_pubkey_from_extkey(): number
  uniffi_ddk_ffi_checksum_func_get_total_input_vsize(): number
  uniffi_ddk_ffi_checksum_func_get_xpub_from_xpriv(): number
  uniffi_ddk_ffi_checksum_func_sign_accept(): number
  uniffi_ddk_ffi_checksum_func_sign_accept_spliced(): number
  uniffi_ddk_ffi_checksum_func_sign_contract_cet(): number
  uniffi_ddk_ffi_checksum_func_sign_contract_refund(): number
  uniffi_ddk_ffi_checksum_func_sign_funding_psbt_with_descriptor(): number
  uniffi_ddk_ffi_checksum_func_validate_accept(): number
  uniffi_ddk_ffi_checksum_func_validate_offer(): number
  uniffi_ddk_ffi_checksum_func_validate_sign(): number
  uniffi_ddk_ffi_checksum_func_verify_cet_adaptor_sigs_from_oracle_info(): number
  uniffi_ddk_ffi_checksum_func_version(): number
  uniffi_ddk_ffi_checksum_constructor_contractkeyprovider_from_descriptor(): number
  uniffi_ddk_ffi_checksum_constructor_contractkeyprovider_from_mnemonic(): number
  uniffi_ddk_ffi_checksum_constructor_contractkeyprovider_from_seed(): number
  uniffi_ddk_ffi_checksum_constructor_contractkeyprovider_from_xprv(): number
  uniffi_ddk_ffi_checksum_method_contractkeyprovider_funding_pubkey(): number
  // Codegen call sites use these via `nativeModule().rustbuffer_alloc(...)`
  // and `nativeModule().rustbuffer_free(...)`. The runtime's registered
  // module exposes them as method properties.
  rustbuffer_alloc(n: number): Uint8Array
  rustbuffer_free(view: Uint8Array): void
}

let _nativeModule: NativeModuleInterface | undefined
const getter: () => NativeModuleInterface = () => {
  if (!_nativeModule) {
    const libPath = resolveLibPath({
      crateName: 'ddk_ffi',
      callerUrl: import.meta.url,
      npmPackageBase: '@bennyblader/ddk-ts-',
      tripleStyle: 'node',
    })
    const mod_ = UniffiNativeModule.open(libPath)
    _nativeModule = mod_.register(DEFINITIONS) as unknown as NativeModuleInterface
  }
  return _nativeModule
}
export default getter

// Structs and function types for calling back into Typescript from Rust.
export type UniffiRustFutureContinuationCallback = (data: bigint, pollResult: number) => void
export type UniffiForeignFutureDroppedCallback = (handle: bigint) => void
export type UniffiForeignFutureDroppedCallbackStruct = {
  handle: bigint
  free: UniffiForeignFutureDroppedCallback
}
