// Generated by uniffi-bindgen-react-native — do not edit.
export * from './ddk_ffi.js'
import * as ddk_ffi from './ddk_ffi.js'

let initialized = false
if (!initialized) {
  ddk_ffi.default.initialize()
  initialized = true
}

export async function uniffiInitAsync() {
  /* sync flavor: no-op */
}

export default {
  ddk_ffi,
}
