rust:
  directory: ../ddk-ffi
  manifestPath: Cargo.toml

bindings:
  cpp: cpp
  ts: src

android:
  directory: android
  packageName: com.ddkrn

ios:
  directory: ios
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
  frameworkName: ios/DdkRn

turboModule:
  cpp: cpp
  ts: src
  spec: NativeDdkRn
