// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!

/* tslint:disable */
/* eslint-disable */
// @ts-nocheck

import {
  type StructuralEquality as UniffiStructuralEquality,
  type UniffiForeignFuture as RuntimeUniffiForeignFuture,
  type UniffiRustCallStatus,
  type UniffiGcObject,
  type UniffiRustFutureContinuationCallback as RuntimeUniffiRustFutureContinuationCallback,
  type UniffiResult,
} from '@ubjs/core';

interface NativeModuleInterface {
  ubrn_uniffi_internal_fn_func_ffi__string_to_byte_length(
    string: string,
    uniffi_out_err: UniffiRustCallStatus
  ): number;
  ubrn_uniffi_internal_fn_func_ffi__string_to_buffer(
    string: string,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_internal_fn_func_ffi__string_from_buffer(
    buffer: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): string;
  ubrn_uniffi_internal_fn_func_ffi__read_string_from_buffer(
    buffer: any,
    offset: number,
    length: number
  ): string;
  ubrn_ffi_ddk_ffi_rust_future_poll_u8(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint
  ): void;
  ubrn_ffi_ddk_ffi_rust_future_cancel_u8(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_complete_u8(
    handle: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): number;
  ubrn_ffi_ddk_ffi_rust_future_free_u8(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_poll_i8(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint
  ): void;
  ubrn_ffi_ddk_ffi_rust_future_cancel_i8(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_complete_i8(
    handle: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): number;
  ubrn_ffi_ddk_ffi_rust_future_free_i8(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_poll_u16(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint
  ): void;
  ubrn_ffi_ddk_ffi_rust_future_cancel_u16(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_complete_u16(
    handle: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): number;
  ubrn_ffi_ddk_ffi_rust_future_free_u16(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_poll_i16(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint
  ): void;
  ubrn_ffi_ddk_ffi_rust_future_cancel_i16(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_complete_i16(
    handle: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): number;
  ubrn_ffi_ddk_ffi_rust_future_free_i16(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_poll_u32(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint
  ): void;
  ubrn_ffi_ddk_ffi_rust_future_cancel_u32(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_complete_u32(
    handle: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): number;
  ubrn_ffi_ddk_ffi_rust_future_free_u32(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_poll_i32(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint
  ): void;
  ubrn_ffi_ddk_ffi_rust_future_cancel_i32(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_complete_i32(
    handle: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): number;
  ubrn_ffi_ddk_ffi_rust_future_free_i32(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_poll_u64(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint
  ): void;
  ubrn_ffi_ddk_ffi_rust_future_cancel_u64(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_complete_u64(
    handle: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): bigint;
  ubrn_ffi_ddk_ffi_rust_future_free_u64(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_poll_i64(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint
  ): void;
  ubrn_ffi_ddk_ffi_rust_future_cancel_i64(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_complete_i64(
    handle: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): bigint;
  ubrn_ffi_ddk_ffi_rust_future_free_i64(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_poll_f32(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint
  ): void;
  ubrn_ffi_ddk_ffi_rust_future_cancel_f32(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_complete_f32(
    handle: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): number;
  ubrn_ffi_ddk_ffi_rust_future_free_f32(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_poll_f64(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint
  ): void;
  ubrn_ffi_ddk_ffi_rust_future_cancel_f64(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_complete_f64(
    handle: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): number;
  ubrn_ffi_ddk_ffi_rust_future_free_f64(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_poll_rust_buffer(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint
  ): void;
  ubrn_ffi_ddk_ffi_rust_future_cancel_rust_buffer(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_complete_rust_buffer(
    handle: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_ffi_ddk_ffi_rust_future_free_rust_buffer(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_poll_void(
    handle: bigint,
    callback: UniffiRustFutureContinuationCallback,
    callbackData: bigint
  ): void;
  ubrn_ffi_ddk_ffi_rust_future_cancel_void(handle: bigint): void;
  ubrn_ffi_ddk_ffi_rust_future_complete_void(
    handle: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): void;
  ubrn_ffi_ddk_ffi_rust_future_free_void(handle: bigint): void;
  ubrn_uniffi_ddk_ffi_fn_func_add_signature_to_transaction(
    tx: Uint8Array,
    signature: Uint8Array,
    pubkey: Uint8Array,
    inputIndex: number,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_convert_mnemonic_to_seed(
    mnemonic: Uint8Array,
    passphrase: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_create_cet(
    localOutput: Uint8Array,
    localPayoutSerialId: bigint,
    remoteOutput: Uint8Array,
    remotePayoutSerialId: bigint,
    fundTxId: Uint8Array,
    fundVout: number,
    lockTime: number,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_points_from_oracle_info(
    oracleInfo: Uint8Array,
    msgs: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_signature_from_oracle_info(
    cet: Uint8Array,
    oracleInfo: Uint8Array,
    fundingSk: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    totalCollateral: bigint,
    msgs: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_sigs_from_oracle_info(
    cets: Uint8Array,
    oracleInfo: Uint8Array,
    fundingSecretKey: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    fundOutputValue: bigint,
    msgs: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_sigs_from_points(
    cets: Uint8Array,
    adaptorPoints: Uint8Array,
    fundingSecretKey: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    fundOutputValue: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_create_cets(
    fundTxId: Uint8Array,
    fundVout: number,
    localFinalScriptPubkey: Uint8Array,
    remoteFinalScriptPubkey: Uint8Array,
    outcomes: Uint8Array,
    lockTime: number,
    localSerialId: bigint,
    remoteSerialId: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_create_dlc_transactions(
    outcomes: Uint8Array,
    localParams: Uint8Array,
    remoteParams: Uint8Array,
    refundLocktime: number,
    feeRate: bigint,
    fundLockTime: number,
    cetLockTime: number,
    fundOutputSerialId: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_create_extkey_from_parent_path(
    extkey: Uint8Array,
    path: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_create_extkey_from_seed(
    seed: Uint8Array,
    network: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_create_fund_tx_locking_script(
    localFundPubkey: Uint8Array,
    remoteFundPubkey: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_create_refund_transaction(
    localFinalScriptPubkey: Uint8Array,
    remoteFinalScriptPubkey: Uint8Array,
    localAmount: bigint,
    remoteAmount: bigint,
    lockTime: number,
    fundTxId: Uint8Array,
    fundVout: number,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_create_spliced_dlc_transactions(
    outcomes: Uint8Array,
    localParams: Uint8Array,
    remoteParams: Uint8Array,
    refundLocktime: number,
    feeRate: bigint,
    fundLockTime: number,
    cetLockTime: number,
    fundOutputSerialId: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_create_xpriv_from_parent_path(
    seedOrXpriv: Uint8Array,
    baseDerivationPath: Uint8Array,
    network: Uint8Array,
    path: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_extract_ecdsa_signature_from_oracle_signatures(
    oracleSignatures: Uint8Array,
    adaptorSignature: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_get_cet_adaptor_signature_inputs(
    cet: Uint8Array,
    oracleInfo: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    fundOutputValue: bigint,
    msgs: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_get_cet_sighash(
    cet: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    fundOutputValue: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_get_change_output_and_fees(
    params: Uint8Array,
    feeRate: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_get_pubkey_from_extkey(
    extkey: Uint8Array,
    network: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_get_raw_funding_transaction_input_signature(
    fundingTransaction: Uint8Array,
    privkey: Uint8Array,
    prevTxId: Uint8Array,
    prevTxVout: number,
    value: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_get_total_input_vsize(
    inputs: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): number;
  ubrn_uniffi_ddk_ffi_fn_func_get_xpub_from_xpriv(
    xpriv: Uint8Array,
    network: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_is_dust_output(
    output: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): number;
  ubrn_uniffi_ddk_ffi_fn_func_sign_cet(
    cet: Uint8Array,
    adaptorSignature: Uint8Array,
    oracleSignatures: Uint8Array,
    fundingSecretKey: Uint8Array,
    otherPubkey: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    fundOutputValue: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_sign_fund_transaction_input(
    fundTransaction: Uint8Array,
    privkey: Uint8Array,
    prevTxId: Uint8Array,
    prevTxVout: number,
    value: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_sign_multi_sig_input(
    tx: Uint8Array,
    dlcInput: Uint8Array,
    localPrivkey: Uint8Array,
    remoteSignature: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_uniffi_ddk_ffi_fn_func_verify_cet_adaptor_sig_from_oracle_info(
    adaptorSig: Uint8Array,
    cet: Uint8Array,
    oracleInfo: Uint8Array,
    pubkey: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    totalCollateral: bigint,
    msgs: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): number;
  ubrn_uniffi_ddk_ffi_fn_func_verify_cet_adaptor_sigs_from_oracle_info(
    adaptorSigs: Uint8Array,
    cets: Uint8Array,
    oracleInfo: Uint8Array,
    pubkey: Uint8Array,
    fundingScriptPubkey: Uint8Array,
    totalCollateral: bigint,
    msgs: Uint8Array,
    uniffi_out_err: UniffiRustCallStatus
  ): number;
  ubrn_uniffi_ddk_ffi_fn_func_verify_fund_tx_signature(
    fundTx: Uint8Array,
    signature: Uint8Array,
    pubkey: Uint8Array,
    txid: Uint8Array,
    vout: number,
    inputAmount: bigint,
    uniffi_out_err: UniffiRustCallStatus
  ): number;
  ubrn_uniffi_ddk_ffi_fn_func_version(
    uniffi_out_err: UniffiRustCallStatus
  ): Uint8Array;
  ubrn_ffi_ddk_ffi_uniffi_contract_version(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_add_signature_to_transaction(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_convert_mnemonic_to_seed(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_create_cet(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_create_cet_adaptor_points_from_oracle_info(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_create_cet_adaptor_signature_from_oracle_info(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_create_cet_adaptor_sigs_from_oracle_info(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_create_cet_adaptor_sigs_from_points(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_create_cets(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_create_dlc_transactions(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_create_extkey_from_parent_path(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_create_extkey_from_seed(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_create_fund_tx_locking_script(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_create_refund_transaction(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_create_spliced_dlc_transactions(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_create_xpriv_from_parent_path(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_extract_ecdsa_signature_from_oracle_signatures(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_get_cet_adaptor_signature_inputs(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_get_cet_sighash(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_get_change_output_and_fees(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_get_pubkey_from_extkey(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_get_raw_funding_transaction_input_signature(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_get_total_input_vsize(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_get_xpub_from_xpriv(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_is_dust_output(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_sign_cet(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_sign_fund_transaction_input(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_sign_multi_sig_input(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_verify_cet_adaptor_sig_from_oracle_info(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_verify_cet_adaptor_sigs_from_oracle_info(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_verify_fund_tx_signature(): number;
  ubrn_uniffi_ddk_ffi_checksum_func_version(): number;
  // Codegen call sites use these via `nativeModule().rustbuffer_alloc(...)`
  // and `nativeModule().rustbuffer_free(...)`. The JSI host object exposes
  // them as properties; see `props["rustbuffer_alloc"]` / `props["rustbuffer_free"]`
  // in the C++ wrapper template.
  rustbuffer_alloc(n: number): Uint8Array;
  rustbuffer_free(view: Uint8Array): void;
}

const getter: () => NativeModuleInterface = () =>
  (globalThis as any).NativeDdkFfi;
export default getter;

// Structs and function types for calling back into Typescript from Rust.
export type UniffiRustFutureContinuationCallback = (
  data: bigint,
  pollResult: number
) => void;
export type UniffiForeignFutureDroppedCallback = (handle: bigint) => void;
export type UniffiForeignFutureDroppedCallbackStruct = {
  handle: bigint;
  free: UniffiForeignFutureDroppedCallback;
};

// UniffiRustFutureContinuationCallback is generated as part of the component interface's
// ffi_definitions. However, we need it in the runtime.
// We chose to generate the declaration anyway, and use a different declaration in the runtime.
// We perform a compile time check that the two versions are structurally equivalent.
const isRustFutureContinuationCallbackTypeCompatible: UniffiStructuralEquality<
  RuntimeUniffiRustFutureContinuationCallback,
  UniffiRustFutureContinuationCallback
> = true;
