// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import nativeModule from './ddk_ffi-ffi';
import {
  type UniffiRustFutureContinuationCallback,
  type UniffiForeignFutureDroppedCallback,
  type UniffiForeignFutureDroppedCallbackStruct,
} from './ddk_ffi-ffi';
import {
  type UniffiByteArray,
  type UniffiHandle,
  type UniffiRustCallStatus,
  AbstractFfiConverterByteArray,
  FfiConverterArray,
  FfiConverterBool,
  FfiConverterInt32,
  FfiConverterOptional,
  FfiConverterUInt32,
  FfiConverterUInt64,
  FfiConverterUInt8,
  RustBuffer,
  UniffiError,
  UniffiInternalError,
  UniffiRustCaller,
  uniffiCreateFfiConverterString,
  uniffiCreateRecord,
  uniffiTypeNameSymbol,
  variantOrdinalSymbol,
} from '@ubjs/core';
const uniffiCaller = new UniffiRustCaller(() => ({ code: 0 }));

const uniffiIsDebug =
  // @ts-ignore -- The process global might not be defined
  typeof process !== 'object' ||
  // @ts-ignore -- The process global might not be defined
  process?.env?.NODE_ENV !== 'production' ||
  true;

// Public interface members begin here.

export function addSignatureToTransaction(
  tx: Transaction,
  signature: Array<number>,
  pubkey: Array<number>,
  inputIndex: number
): Transaction /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeTransaction.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_add_signature_to_transaction`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_add_signature_to_transaction;
        })()(
          FfiConverterTypeTransaction.lower(
            tx,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            signature,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            pubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt32.lower(inputIndex, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function convertMnemonicToSeed(
  mnemonic: string,
  passphrase: string | undefined
): Array<number> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceUInt8.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_convert_mnemonic_to_seed`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_convert_mnemonic_to_seed;
        })()(
          FfiConverterString.lower(mnemonic, nativeModule().rustbuffer_alloc),
          FfiConverterOptionalString.lower(
            passphrase,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createCet(
  localOutput: TxOutput,
  localPayoutSerialId: bigint,
  remoteOutput: TxOutput,
  remotePayoutSerialId: bigint,
  fundTxId: string,
  fundVout: number,
  lockTime: number
): Transaction /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeTransaction.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(`-- ubrn_uniffi_ddk_ffi_fn_func_create_cet`);
          return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_create_cet;
        })()(
          FfiConverterTypeTxOutput.lower(
            localOutput,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            localPayoutSerialId,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterTypeTxOutput.lower(
            remoteOutput,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            remotePayoutSerialId,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(fundTxId, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(fundVout, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(lockTime, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createCetAdaptorPointsFromOracleInfo(
  oracleInfo: Array<OracleInfo>,
  msgs: Array<Array<Array<Array<number>>>>
): Array<Array<number>> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceSequenceUInt8.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_points_from_oracle_info`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_points_from_oracle_info;
        })()(
          FfiConverterSequenceTypeOracleInfo.lower(
            oracleInfo,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceSequenceSequenceSequenceUInt8.lower(
            msgs,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createCetAdaptorSignatureFromOracleInfo(
  cet: Transaction,
  oracleInfo: OracleInfo,
  fundingSk: Array<number>,
  fundingScriptPubkey: Array<number>,
  totalCollateral: bigint,
  msgs: Array<Array<number>>
): AdaptorSignature /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeAdaptorSignature.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_signature_from_oracle_info`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_signature_from_oracle_info;
        })()(
          FfiConverterTypeTransaction.lower(
            cet,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterTypeOracleInfo.lower(
            oracleInfo,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            fundingSk,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            fundingScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            totalCollateral,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceSequenceUInt8.lower(
            msgs,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createCetAdaptorSigsFromOracleInfo(
  cets: Array<Transaction>,
  oracleInfo: Array<OracleInfo>,
  fundingSecretKey: Array<number>,
  fundingScriptPubkey: Array<number>,
  fundOutputValue: bigint,
  msgs: Array<Array<Array<Array<number>>>>
): Array<AdaptorSignature> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceTypeAdaptorSignature.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_sigs_from_oracle_info`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_sigs_from_oracle_info;
        })()(
          FfiConverterSequenceTypeTransaction.lower(
            cets,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceTypeOracleInfo.lower(
            oracleInfo,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            fundingSecretKey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            fundingScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            fundOutputValue,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceSequenceSequenceSequenceUInt8.lower(
            msgs,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createCetAdaptorSigsFromPoints(
  cets: Array<Transaction>,
  adaptorPoints: Array<Array<number>>,
  fundingSecretKey: Array<number>,
  fundingScriptPubkey: Array<number>,
  fundOutputValue: bigint
): Array<AdaptorSignature> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceTypeAdaptorSignature.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_sigs_from_points`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_sigs_from_points;
        })()(
          FfiConverterSequenceTypeTransaction.lower(
            cets,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceSequenceUInt8.lower(
            adaptorPoints,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            fundingSecretKey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            fundingScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            fundOutputValue,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createCets(
  fundTxId: string,
  fundVout: number,
  localFinalScriptPubkey: Array<number>,
  remoteFinalScriptPubkey: Array<number>,
  outcomes: Array<Payout>,
  lockTime: number,
  localSerialId: bigint,
  remoteSerialId: bigint
): Array<Transaction> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceTypeTransaction.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(`-- ubrn_uniffi_ddk_ffi_fn_func_create_cets`);
          return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_create_cets;
        })()(
          FfiConverterString.lower(fundTxId, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(fundVout, nativeModule().rustbuffer_alloc),
          FfiConverterSequenceUInt8.lower(
            localFinalScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            remoteFinalScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceTypePayout.lower(
            outcomes,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt32.lower(lockTime, nativeModule().rustbuffer_alloc),
          FfiConverterUInt64.lower(
            localSerialId,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            remoteSerialId,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createDlcTransactions(
  outcomes: Array<Payout>,
  localParams: PartyParams,
  remoteParams: PartyParams,
  refundLocktime: number,
  feeRate: bigint,
  fundLockTime: number,
  cetLockTime: number,
  fundOutputSerialId: bigint
): DlcTransactions /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeDlcTransactions.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_create_dlc_transactions`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_create_dlc_transactions;
        })()(
          FfiConverterSequenceTypePayout.lower(
            outcomes,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterTypePartyParams.lower(
            localParams,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterTypePartyParams.lower(
            remoteParams,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt32.lower(
            refundLocktime,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(feeRate, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(
            fundLockTime,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt32.lower(
            cetLockTime,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            fundOutputSerialId,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createExtkeyFromParentPath(
  extkey: Array<number>,
  path: string
): Array<number> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceUInt8.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_create_extkey_from_parent_path`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_create_extkey_from_parent_path;
        })()(
          FfiConverterSequenceUInt8.lower(
            extkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(path, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createExtkeyFromSeed(
  seed: Array<number>,
  network: string
): Array<number> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceUInt8.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_create_extkey_from_seed`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_create_extkey_from_seed;
        })()(
          FfiConverterSequenceUInt8.lower(
            seed,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(network, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createFundTxLockingScript(
  localFundPubkey: Array<number>,
  remoteFundPubkey: Array<number>
): Array<number> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceUInt8.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_create_fund_tx_locking_script`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_create_fund_tx_locking_script;
        })()(
          FfiConverterSequenceUInt8.lower(
            localFundPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            remoteFundPubkey,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createRefundTransaction(
  localFinalScriptPubkey: Array<number>,
  remoteFinalScriptPubkey: Array<number>,
  localAmount: bigint,
  remoteAmount: bigint,
  lockTime: number,
  fundTxId: string,
  fundVout: number
): Transaction /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeTransaction.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_create_refund_transaction`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_create_refund_transaction;
        })()(
          FfiConverterSequenceUInt8.lower(
            localFinalScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            remoteFinalScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            localAmount,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            remoteAmount,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt32.lower(lockTime, nativeModule().rustbuffer_alloc),
          FfiConverterString.lower(fundTxId, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(fundVout, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createSplicedDlcTransactions(
  outcomes: Array<Payout>,
  localParams: PartyParams,
  remoteParams: PartyParams,
  refundLocktime: number,
  feeRate: bigint,
  fundLockTime: number,
  cetLockTime: number,
  fundOutputSerialId: bigint
): DlcTransactions /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeDlcTransactions.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_create_spliced_dlc_transactions`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_create_spliced_dlc_transactions;
        })()(
          FfiConverterSequenceTypePayout.lower(
            outcomes,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterTypePartyParams.lower(
            localParams,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterTypePartyParams.lower(
            remoteParams,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt32.lower(
            refundLocktime,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(feeRate, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(
            fundLockTime,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt32.lower(
            cetLockTime,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            fundOutputSerialId,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createXprivFromParentPath(
  seedOrXpriv: Array<number>,
  baseDerivationPath: string,
  network: string,
  path: string
): Array<number> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceUInt8.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_create_xpriv_from_parent_path`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_create_xpriv_from_parent_path;
        })()(
          FfiConverterSequenceUInt8.lower(
            seedOrXpriv,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(
            baseDerivationPath,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(network, nativeModule().rustbuffer_alloc),
          FfiConverterString.lower(path, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function extractEcdsaSignatureFromOracleSignatures(
  oracleSignatures: Array<Array<number>>,
  adaptorSignature: Array<number>
): Array<number> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceUInt8.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_extract_ecdsa_signature_from_oracle_signatures`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_extract_ecdsa_signature_from_oracle_signatures;
        })()(
          FfiConverterSequenceSequenceUInt8.lower(
            oracleSignatures,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            adaptorSignature,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function getCetAdaptorSignatureInputs(
  cet: Transaction,
  oracleInfo: Array<OracleInfo>,
  fundingScriptPubkey: Array<number>,
  fundOutputValue: bigint,
  msgs: Array<Array<Array<number>>>
): CetAdaptorSignatureDebugInfo /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeCetAdaptorSignatureDebugInfo.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_get_cet_adaptor_signature_inputs`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_get_cet_adaptor_signature_inputs;
        })()(
          FfiConverterTypeTransaction.lower(
            cet,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceTypeOracleInfo.lower(
            oracleInfo,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            fundingScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            fundOutputValue,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceSequenceSequenceUInt8.lower(
            msgs,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function getCetSighash(
  cet: Transaction,
  fundingScriptPubkey: Array<number>,
  fundOutputValue: bigint
): Array<number> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceUInt8.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(`-- ubrn_uniffi_ddk_ffi_fn_func_get_cet_sighash`);
          return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_get_cet_sighash;
        })()(
          FfiConverterTypeTransaction.lower(
            cet,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            fundingScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            fundOutputValue,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function getChangeOutputAndFees(
  params: PartyParams,
  feeRate: bigint
): ChangeOutputAndFees /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeChangeOutputAndFees.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_get_change_output_and_fees`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_get_change_output_and_fees;
        })()(
          FfiConverterTypePartyParams.lower(
            params,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(feeRate, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function getPubkeyFromExtkey(
  extkey: Array<number>,
  network: string
): Array<number> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceUInt8.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_get_pubkey_from_extkey`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_get_pubkey_from_extkey;
        })()(
          FfiConverterSequenceUInt8.lower(
            extkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(network, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function getRawFundingTransactionInputSignature(
  fundingTransaction: Transaction,
  privkey: Array<number>,
  prevTxId: string,
  prevTxVout: number,
  value: bigint
): Array<number> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceUInt8.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_get_raw_funding_transaction_input_signature`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_get_raw_funding_transaction_input_signature;
        })()(
          FfiConverterTypeTransaction.lower(
            fundingTransaction,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            privkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(prevTxId, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(prevTxVout, nativeModule().rustbuffer_alloc),
          FfiConverterUInt64.lower(value, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function getTotalInputVsize(inputs: Array<TxInputInfo>): number {
  return FfiConverterUInt32.lift(
    uniffiCaller.rustCall(
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(`-- ubrn_uniffi_ddk_ffi_fn_func_get_total_input_vsize`);
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_get_total_input_vsize;
        })()(
          FfiConverterSequenceTypeTxInputInfo.lower(
            inputs,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function getXpubFromXpriv(
  xpriv: Array<number>,
  network: string
): Array<number> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceUInt8.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(`-- ubrn_uniffi_ddk_ffi_fn_func_get_xpub_from_xpriv`);
          return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_get_xpub_from_xpriv;
        })()(
          FfiConverterSequenceUInt8.lower(
            xpriv,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(network, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function isDustOutput(output: TxOutput): boolean {
  return FfiConverterBool.lift(
    uniffiCaller.rustCall(
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(`-- ubrn_uniffi_ddk_ffi_fn_func_is_dust_output`);
          return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_is_dust_output;
        })()(
          FfiConverterTypeTxOutput.lower(
            output,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function signCet(
  cet: Transaction,
  adaptorSignature: Array<number>,
  oracleSignatures: Array<Array<number>>,
  fundingSecretKey: Array<number>,
  otherPubkey: Array<number>,
  fundingScriptPubkey: Array<number>,
  fundOutputValue: bigint
): Transaction /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeTransaction.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(`-- ubrn_uniffi_ddk_ffi_fn_func_sign_cet`);
          return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_sign_cet;
        })()(
          FfiConverterTypeTransaction.lower(
            cet,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            adaptorSignature,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceSequenceUInt8.lower(
            oracleSignatures,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            fundingSecretKey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            otherPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            fundingScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            fundOutputValue,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function signFundTransactionInput(
  fundTransaction: Transaction,
  privkey: Array<number>,
  prevTxId: string,
  prevTxVout: number,
  value: bigint
): Transaction /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeTransaction.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_sign_fund_transaction_input`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_sign_fund_transaction_input;
        })()(
          FfiConverterTypeTransaction.lower(
            fundTransaction,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            privkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(prevTxId, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(prevTxVout, nativeModule().rustbuffer_alloc),
          FfiConverterUInt64.lower(value, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function signMultiSigInput(
  tx: Transaction,
  dlcInput: DlcInputInfo,
  localPrivkey: Array<number>,
  remoteSignature: Array<number>
): Transaction /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeTransaction.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(`-- ubrn_uniffi_ddk_ffi_fn_func_sign_multi_sig_input`);
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_sign_multi_sig_input;
        })()(
          FfiConverterTypeTransaction.lower(
            tx,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterTypeDlcInputInfo.lower(
            dlcInput,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            localPrivkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            remoteSignature,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function verifyCetAdaptorSigFromOracleInfo(
  adaptorSig: AdaptorSignature,
  cet: Transaction,
  oracleInfo: Array<OracleInfo>,
  pubkey: Array<number>,
  fundingScriptPubkey: Array<number>,
  totalCollateral: bigint,
  msgs: Array<Array<Array<number>>>
): boolean {
  return FfiConverterBool.lift(
    uniffiCaller.rustCall(
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_verify_cet_adaptor_sig_from_oracle_info`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_verify_cet_adaptor_sig_from_oracle_info;
        })()(
          FfiConverterTypeAdaptorSignature.lower(
            adaptorSig,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterTypeTransaction.lower(
            cet,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceTypeOracleInfo.lower(
            oracleInfo,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            pubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            fundingScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            totalCollateral,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceSequenceSequenceUInt8.lower(
            msgs,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function verifyCetAdaptorSigsFromOracleInfo(
  adaptorSigs: Array<AdaptorSignature>,
  cets: Array<Transaction>,
  oracleInfo: Array<OracleInfo>,
  pubkey: Array<number>,
  fundingScriptPubkey: Array<number>,
  totalCollateral: bigint,
  msgs: Array<Array<Array<Array<number>>>>
): boolean {
  return FfiConverterBool.lift(
    uniffiCaller.rustCall(
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_verify_cet_adaptor_sigs_from_oracle_info`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_verify_cet_adaptor_sigs_from_oracle_info;
        })()(
          FfiConverterSequenceTypeAdaptorSignature.lower(
            adaptorSigs,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceTypeTransaction.lower(
            cets,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceTypeOracleInfo.lower(
            oracleInfo,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            pubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            fundingScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            totalCollateral,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceSequenceSequenceSequenceUInt8.lower(
            msgs,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function verifyFundTxSignature(
  fundTx: Transaction,
  signature: Array<number>,
  pubkey: Array<number>,
  txid: string,
  vout: number,
  inputAmount: bigint
): boolean /*throws*/ {
  return FfiConverterBool.lift(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(
            `-- ubrn_uniffi_ddk_ffi_fn_func_verify_fund_tx_signature`
          );
          return nativeModule()
            .ubrn_uniffi_ddk_ffi_fn_func_verify_fund_tx_signature;
        })()(
          FfiConverterTypeTransaction.lower(
            fundTx,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            signature,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceUInt8.lower(
            pubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(txid, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(vout, nativeModule().rustbuffer_alloc),
          FfiConverterUInt64.lower(
            inputAmount,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function version(): string {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterString.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCall(
      /*caller:*/ (callStatus) => {
        return (() => {
          console.debug(`-- ubrn_uniffi_ddk_ffi_fn_func_version`);
          return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_version;
        })()(callStatus);
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export type AdaptorSignature = {
  signature: Array<number>;
  proof: Array<number>;
};

/**
 * Generated factory for {@link AdaptorSignature} record objects.
 */
export const AdaptorSignature = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<AdaptorSignature, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<AdaptorSignature>,
  });
})();

const FfiConverterTypeAdaptorSignature = (() => {
  type TypeName = AdaptorSignature;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        signature: FfiConverterSequenceUInt8.read(from),
        proof: FfiConverterSequenceUInt8.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterSequenceUInt8.write(value.signature, into);
      FfiConverterSequenceUInt8.write(value.proof, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterSequenceUInt8.allocationSize(value.signature) +
        FfiConverterSequenceUInt8.allocationSize(value.proof)
      );
    }
  }
  return new FFIConverter();
})();

// Hermes (React Native ≥ 0.74) ships TextEncoder and encodeInto, but not
// TextDecoder. For single-string decode (bytesToString), we polyfill via the
// C++ string_from_buffer helper using a duck-typed object matching the
// standard TextDecoder.decode signature. Once Hermes ships a real
// TextDecoder, the `typeof` check will pick it up automatically.
//
// For array-of-strings decode (readStringFromBuffer), we keep a dedicated C++
// helper: the polyfill path (new Uint8Array view + decode) measured ~40%
// slower on getStringArray benchmarks than a direct (buf, offset, length)
// call, due to the per-read view allocation and extra property lookups in
// string_from_buffer.
const stringConverter = (() => {
  const encoder = new TextEncoder();
  const decoder: { decode(input: UniffiByteArray): string } =
    typeof TextDecoder !== 'undefined'
      ? new TextDecoder()
      : {
          decode: (bytes: UniffiByteArray) =>
            nativeModule().ubrn_uniffi_internal_fn_func_ffi__string_from_buffer(
              bytes,
              undefined as any
            ) as string,
        };
  return {
    // Single-string lower() uses the C++ helper — TextEncoder.encode
    // measured ~43% slower on takeString benchmarks.
    stringToBytes: (s: string) =>
      nativeModule().ubrn_uniffi_internal_fn_func_ffi__string_to_buffer(
        s,
        undefined as any
      ),
    bytesToString: (ab: UniffiByteArray) => decoder.decode(ab),
    // Direct C++ call — bypasses uniffiCaller.rustCall() overhead.
    // Matters for N-element arrays.
    stringByteLength: (s: string) =>
      nativeModule().ubrn_uniffi_internal_fn_func_ffi__string_to_byte_length(
        s,
        undefined as any
      ) as number,
    // Encode directly into the RustBuffer backing store via
    // TextEncoder.encodeInto — zero intermediate allocation. Replaces
    // the old C++ write_string_into_buffer helper.
    writeStringIntoBuffer: (s: string, buf: any, offset: number): number => {
      const view = new Uint8Array(
        buf.arrayBuffer,
        offset,
        buf.arrayBuffer.byteLength - offset
      );
      return encoder.encodeInto(s, view).written;
    },
    // Dedicated C++ helper — avoids per-read Uint8Array allocation and
    // the double property-lookup in string_from_buffer.
    readStringFromBuffer: (buf: any, offset: number, length: number): string =>
      nativeModule().ubrn_uniffi_internal_fn_func_ffi__read_string_from_buffer(
        buf,
        offset,
        length
      ) as string,
  };
})();
const FfiConverterString = uniffiCreateFfiConverterString(stringConverter);

export type CetAdaptorSignatureDebugInfo = {
  sighash: Array<number>;
  adaptorPoint: Array<number>;
  inputIndex: number;
  scriptPubkey: Array<number>;
  value: bigint;
  cetTxid: string;
  cetRaw: Array<number>;
};

/**
 * Generated factory for {@link CetAdaptorSignatureDebugInfo} record objects.
 */
export const CetAdaptorSignatureDebugInfo = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<
      CetAdaptorSignatureDebugInfo,
      ReturnType<typeof defaults>
    >(defaults);
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () =>
      Object.freeze(defaults()) as Partial<CetAdaptorSignatureDebugInfo>,
  });
})();

const FfiConverterTypeCetAdaptorSignatureDebugInfo = (() => {
  type TypeName = CetAdaptorSignatureDebugInfo;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        sighash: FfiConverterSequenceUInt8.read(from),
        adaptorPoint: FfiConverterSequenceUInt8.read(from),
        inputIndex: FfiConverterUInt32.read(from),
        scriptPubkey: FfiConverterSequenceUInt8.read(from),
        value: FfiConverterUInt64.read(from),
        cetTxid: FfiConverterString.read(from),
        cetRaw: FfiConverterSequenceUInt8.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterSequenceUInt8.write(value.sighash, into);
      FfiConverterSequenceUInt8.write(value.adaptorPoint, into);
      FfiConverterUInt32.write(value.inputIndex, into);
      FfiConverterSequenceUInt8.write(value.scriptPubkey, into);
      FfiConverterUInt64.write(value.value, into);
      FfiConverterString.write(value.cetTxid, into);
      FfiConverterSequenceUInt8.write(value.cetRaw, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterSequenceUInt8.allocationSize(value.sighash) +
        FfiConverterSequenceUInt8.allocationSize(value.adaptorPoint) +
        FfiConverterUInt32.allocationSize(value.inputIndex) +
        FfiConverterSequenceUInt8.allocationSize(value.scriptPubkey) +
        FfiConverterUInt64.allocationSize(value.value) +
        FfiConverterString.allocationSize(value.cetTxid) +
        FfiConverterSequenceUInt8.allocationSize(value.cetRaw)
      );
    }
  }
  return new FFIConverter();
})();

export type TxOutput = {
  value: bigint;
  scriptPubkey: Array<number>;
};

/**
 * Generated factory for {@link TxOutput} record objects.
 */
export const TxOutput = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<TxOutput, ReturnType<typeof defaults>>(defaults);
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<TxOutput>,
  });
})();

const FfiConverterTypeTxOutput = (() => {
  type TypeName = TxOutput;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        value: FfiConverterUInt64.read(from),
        scriptPubkey: FfiConverterSequenceUInt8.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterUInt64.write(value.value, into);
      FfiConverterSequenceUInt8.write(value.scriptPubkey, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterUInt64.allocationSize(value.value) +
        FfiConverterSequenceUInt8.allocationSize(value.scriptPubkey)
      );
    }
  }
  return new FFIConverter();
})();

export type ChangeOutputAndFees = {
  changeOutput: TxOutput;
  fundFee: bigint;
  cetFee: bigint;
};

/**
 * Generated factory for {@link ChangeOutputAndFees} record objects.
 */
export const ChangeOutputAndFees = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<ChangeOutputAndFees, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<ChangeOutputAndFees>,
  });
})();

const FfiConverterTypeChangeOutputAndFees = (() => {
  type TypeName = ChangeOutputAndFees;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        changeOutput: FfiConverterTypeTxOutput.read(from),
        fundFee: FfiConverterUInt64.read(from),
        cetFee: FfiConverterUInt64.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterTypeTxOutput.write(value.changeOutput, into);
      FfiConverterUInt64.write(value.fundFee, into);
      FfiConverterUInt64.write(value.cetFee, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterTypeTxOutput.allocationSize(value.changeOutput) +
        FfiConverterUInt64.allocationSize(value.fundFee) +
        FfiConverterUInt64.allocationSize(value.cetFee)
      );
    }
  }
  return new FFIConverter();
})();

export type TxInput = {
  txid: string;
  vout: number;
  scriptSig: Array<number>;
  sequence: number;
  witness: Array<Array<number>>;
};

/**
 * Generated factory for {@link TxInput} record objects.
 */
export const TxInput = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<TxInput, ReturnType<typeof defaults>>(defaults);
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<TxInput>,
  });
})();

const FfiConverterTypeTxInput = (() => {
  type TypeName = TxInput;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        txid: FfiConverterString.read(from),
        vout: FfiConverterUInt32.read(from),
        scriptSig: FfiConverterSequenceUInt8.read(from),
        sequence: FfiConverterUInt32.read(from),
        witness: FfiConverterSequenceSequenceUInt8.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterString.write(value.txid, into);
      FfiConverterUInt32.write(value.vout, into);
      FfiConverterSequenceUInt8.write(value.scriptSig, into);
      FfiConverterUInt32.write(value.sequence, into);
      FfiConverterSequenceSequenceUInt8.write(value.witness, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterString.allocationSize(value.txid) +
        FfiConverterUInt32.allocationSize(value.vout) +
        FfiConverterSequenceUInt8.allocationSize(value.scriptSig) +
        FfiConverterUInt32.allocationSize(value.sequence) +
        FfiConverterSequenceSequenceUInt8.allocationSize(value.witness)
      );
    }
  }
  return new FFIConverter();
})();

export type Transaction = {
  version: number;
  lockTime: number;
  inputs: Array<TxInput>;
  outputs: Array<TxOutput>;
  rawBytes: Array<number>;
};

/**
 * Generated factory for {@link Transaction} record objects.
 */
export const Transaction = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<Transaction, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<Transaction>,
  });
})();

const FfiConverterTypeTransaction = (() => {
  type TypeName = Transaction;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        version: FfiConverterInt32.read(from),
        lockTime: FfiConverterUInt32.read(from),
        inputs: FfiConverterSequenceTypeTxInput.read(from),
        outputs: FfiConverterSequenceTypeTxOutput.read(from),
        rawBytes: FfiConverterSequenceUInt8.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterInt32.write(value.version, into);
      FfiConverterUInt32.write(value.lockTime, into);
      FfiConverterSequenceTypeTxInput.write(value.inputs, into);
      FfiConverterSequenceTypeTxOutput.write(value.outputs, into);
      FfiConverterSequenceUInt8.write(value.rawBytes, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterInt32.allocationSize(value.version) +
        FfiConverterUInt32.allocationSize(value.lockTime) +
        FfiConverterSequenceTypeTxInput.allocationSize(value.inputs) +
        FfiConverterSequenceTypeTxOutput.allocationSize(value.outputs) +
        FfiConverterSequenceUInt8.allocationSize(value.rawBytes)
      );
    }
  }
  return new FFIConverter();
})();

export type DlcInputInfo = {
  fundTx: Transaction;
  fundVout: number;
  localFundPubkey: Array<number>;
  remoteFundPubkey: Array<number>;
  fundAmount: bigint;
  maxWitnessLen: number;
  inputSerialId: bigint;
  contractId: Array<number>;
};

/**
 * Generated factory for {@link DlcInputInfo} record objects.
 */
export const DlcInputInfo = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<DlcInputInfo, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<DlcInputInfo>,
  });
})();

const FfiConverterTypeDlcInputInfo = (() => {
  type TypeName = DlcInputInfo;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        fundTx: FfiConverterTypeTransaction.read(from),
        fundVout: FfiConverterUInt32.read(from),
        localFundPubkey: FfiConverterSequenceUInt8.read(from),
        remoteFundPubkey: FfiConverterSequenceUInt8.read(from),
        fundAmount: FfiConverterUInt64.read(from),
        maxWitnessLen: FfiConverterUInt32.read(from),
        inputSerialId: FfiConverterUInt64.read(from),
        contractId: FfiConverterSequenceUInt8.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterTypeTransaction.write(value.fundTx, into);
      FfiConverterUInt32.write(value.fundVout, into);
      FfiConverterSequenceUInt8.write(value.localFundPubkey, into);
      FfiConverterSequenceUInt8.write(value.remoteFundPubkey, into);
      FfiConverterUInt64.write(value.fundAmount, into);
      FfiConverterUInt32.write(value.maxWitnessLen, into);
      FfiConverterUInt64.write(value.inputSerialId, into);
      FfiConverterSequenceUInt8.write(value.contractId, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterTypeTransaction.allocationSize(value.fundTx) +
        FfiConverterUInt32.allocationSize(value.fundVout) +
        FfiConverterSequenceUInt8.allocationSize(value.localFundPubkey) +
        FfiConverterSequenceUInt8.allocationSize(value.remoteFundPubkey) +
        FfiConverterUInt64.allocationSize(value.fundAmount) +
        FfiConverterUInt32.allocationSize(value.maxWitnessLen) +
        FfiConverterUInt64.allocationSize(value.inputSerialId) +
        FfiConverterSequenceUInt8.allocationSize(value.contractId)
      );
    }
  }
  return new FFIConverter();
})();

export type DlcTransactions = {
  fund: Transaction;
  cets: Array<Transaction>;
  refund: Transaction;
  fundingScriptPubkey: Array<number>;
};

/**
 * Generated factory for {@link DlcTransactions} record objects.
 */
export const DlcTransactions = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<DlcTransactions, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<DlcTransactions>,
  });
})();

const FfiConverterTypeDlcTransactions = (() => {
  type TypeName = DlcTransactions;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        fund: FfiConverterTypeTransaction.read(from),
        cets: FfiConverterSequenceTypeTransaction.read(from),
        refund: FfiConverterTypeTransaction.read(from),
        fundingScriptPubkey: FfiConverterSequenceUInt8.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterTypeTransaction.write(value.fund, into);
      FfiConverterSequenceTypeTransaction.write(value.cets, into);
      FfiConverterTypeTransaction.write(value.refund, into);
      FfiConverterSequenceUInt8.write(value.fundingScriptPubkey, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterTypeTransaction.allocationSize(value.fund) +
        FfiConverterSequenceTypeTransaction.allocationSize(value.cets) +
        FfiConverterTypeTransaction.allocationSize(value.refund) +
        FfiConverterSequenceUInt8.allocationSize(value.fundingScriptPubkey)
      );
    }
  }
  return new FFIConverter();
})();

export type OracleInfo = {
  publicKey: Array<number>;
  nonces: Array<Array<number>>;
};

/**
 * Generated factory for {@link OracleInfo} record objects.
 */
export const OracleInfo = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<OracleInfo, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<OracleInfo>,
  });
})();

const FfiConverterTypeOracleInfo = (() => {
  type TypeName = OracleInfo;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        publicKey: FfiConverterSequenceUInt8.read(from),
        nonces: FfiConverterSequenceSequenceUInt8.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterSequenceUInt8.write(value.publicKey, into);
      FfiConverterSequenceSequenceUInt8.write(value.nonces, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterSequenceUInt8.allocationSize(value.publicKey) +
        FfiConverterSequenceSequenceUInt8.allocationSize(value.nonces)
      );
    }
  }
  return new FFIConverter();
})();

export type TxInputInfo = {
  txid: string;
  vout: number;
  scriptSig: Array<number>;
  maxWitnessLength: number;
  serialId: bigint;
};

/**
 * Generated factory for {@link TxInputInfo} record objects.
 */
export const TxInputInfo = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<TxInputInfo, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<TxInputInfo>,
  });
})();

const FfiConverterTypeTxInputInfo = (() => {
  type TypeName = TxInputInfo;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        txid: FfiConverterString.read(from),
        vout: FfiConverterUInt32.read(from),
        scriptSig: FfiConverterSequenceUInt8.read(from),
        maxWitnessLength: FfiConverterUInt32.read(from),
        serialId: FfiConverterUInt64.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterString.write(value.txid, into);
      FfiConverterUInt32.write(value.vout, into);
      FfiConverterSequenceUInt8.write(value.scriptSig, into);
      FfiConverterUInt32.write(value.maxWitnessLength, into);
      FfiConverterUInt64.write(value.serialId, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterString.allocationSize(value.txid) +
        FfiConverterUInt32.allocationSize(value.vout) +
        FfiConverterSequenceUInt8.allocationSize(value.scriptSig) +
        FfiConverterUInt32.allocationSize(value.maxWitnessLength) +
        FfiConverterUInt64.allocationSize(value.serialId)
      );
    }
  }
  return new FFIConverter();
})();

export type PartyParams = {
  fundPubkey: Array<number>;
  changeScriptPubkey: Array<number>;
  changeSerialId: bigint;
  payoutScriptPubkey: Array<number>;
  payoutSerialId: bigint;
  inputs: Array<TxInputInfo>;
  inputAmount: bigint;
  collateral: bigint;
  dlcInputs: Array<DlcInputInfo>;
};

/**
 * Generated factory for {@link PartyParams} record objects.
 */
export const PartyParams = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<PartyParams, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<PartyParams>,
  });
})();

const FfiConverterTypePartyParams = (() => {
  type TypeName = PartyParams;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        fundPubkey: FfiConverterSequenceUInt8.read(from),
        changeScriptPubkey: FfiConverterSequenceUInt8.read(from),
        changeSerialId: FfiConverterUInt64.read(from),
        payoutScriptPubkey: FfiConverterSequenceUInt8.read(from),
        payoutSerialId: FfiConverterUInt64.read(from),
        inputs: FfiConverterSequenceTypeTxInputInfo.read(from),
        inputAmount: FfiConverterUInt64.read(from),
        collateral: FfiConverterUInt64.read(from),
        dlcInputs: FfiConverterSequenceTypeDlcInputInfo.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterSequenceUInt8.write(value.fundPubkey, into);
      FfiConverterSequenceUInt8.write(value.changeScriptPubkey, into);
      FfiConverterUInt64.write(value.changeSerialId, into);
      FfiConverterSequenceUInt8.write(value.payoutScriptPubkey, into);
      FfiConverterUInt64.write(value.payoutSerialId, into);
      FfiConverterSequenceTypeTxInputInfo.write(value.inputs, into);
      FfiConverterUInt64.write(value.inputAmount, into);
      FfiConverterUInt64.write(value.collateral, into);
      FfiConverterSequenceTypeDlcInputInfo.write(value.dlcInputs, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterSequenceUInt8.allocationSize(value.fundPubkey) +
        FfiConverterSequenceUInt8.allocationSize(value.changeScriptPubkey) +
        FfiConverterUInt64.allocationSize(value.changeSerialId) +
        FfiConverterSequenceUInt8.allocationSize(value.payoutScriptPubkey) +
        FfiConverterUInt64.allocationSize(value.payoutSerialId) +
        FfiConverterSequenceTypeTxInputInfo.allocationSize(value.inputs) +
        FfiConverterUInt64.allocationSize(value.inputAmount) +
        FfiConverterUInt64.allocationSize(value.collateral) +
        FfiConverterSequenceTypeDlcInputInfo.allocationSize(value.dlcInputs)
      );
    }
  }
  return new FFIConverter();
})();

export type Payout = {
  offer: bigint;
  accept: bigint;
};

/**
 * Generated factory for {@link Payout} record objects.
 */
export const Payout = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<Payout, ReturnType<typeof defaults>>(defaults);
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<Payout>,
  });
})();

const FfiConverterTypePayout = (() => {
  type TypeName = Payout;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        offer: FfiConverterUInt64.read(from),
        accept: FfiConverterUInt64.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterUInt64.write(value.offer, into);
      FfiConverterUInt64.write(value.accept, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterUInt64.allocationSize(value.offer) +
        FfiConverterUInt64.allocationSize(value.accept)
      );
    }
  }
  return new FFIConverter();
})();

// Flat error type: DlcError
export enum DlcError_Tags {
  InvalidSignature = 'InvalidSignature',
  InvalidPublicKey = 'InvalidPublicKey',
  InvalidTransaction = 'InvalidTransaction',
  InsufficientFunds = 'InsufficientFunds',
  InvalidArgument = 'InvalidArgument',
  SerializationError = 'SerializationError',
  Secp256k1Error = 'Secp256k1Error',
  MiniscriptError = 'MiniscriptError',
  InvalidNetwork = 'InvalidNetwork',
  KeyError = 'KeyError',
}
export const DlcError = (() => {
  class InvalidSignature extends UniffiError {
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [uniffiTypeNameSymbol]: string = 'DlcError';
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [variantOrdinalSymbol] = 1;

    readonly tag = DlcError_Tags.InvalidSignature;

    constructor(message: string) {
      super('DlcError', 'InvalidSignature', message);
    }

    static instanceOf(e: any): e is InvalidSignature {
      return instanceOf(e) && (e as any)[variantOrdinalSymbol] === 1;
    }
  }
  class InvalidPublicKey extends UniffiError {
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [uniffiTypeNameSymbol]: string = 'DlcError';
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [variantOrdinalSymbol] = 2;

    readonly tag = DlcError_Tags.InvalidPublicKey;

    constructor(message: string) {
      super('DlcError', 'InvalidPublicKey', message);
    }

    static instanceOf(e: any): e is InvalidPublicKey {
      return instanceOf(e) && (e as any)[variantOrdinalSymbol] === 2;
    }
  }
  class InvalidTransaction extends UniffiError {
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [uniffiTypeNameSymbol]: string = 'DlcError';
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [variantOrdinalSymbol] = 3;

    readonly tag = DlcError_Tags.InvalidTransaction;

    constructor(message: string) {
      super('DlcError', 'InvalidTransaction', message);
    }

    static instanceOf(e: any): e is InvalidTransaction {
      return instanceOf(e) && (e as any)[variantOrdinalSymbol] === 3;
    }
  }
  class InsufficientFunds extends UniffiError {
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [uniffiTypeNameSymbol]: string = 'DlcError';
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [variantOrdinalSymbol] = 4;

    readonly tag = DlcError_Tags.InsufficientFunds;

    constructor(message: string) {
      super('DlcError', 'InsufficientFunds', message);
    }

    static instanceOf(e: any): e is InsufficientFunds {
      return instanceOf(e) && (e as any)[variantOrdinalSymbol] === 4;
    }
  }
  class InvalidArgument extends UniffiError {
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [uniffiTypeNameSymbol]: string = 'DlcError';
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [variantOrdinalSymbol] = 5;

    readonly tag = DlcError_Tags.InvalidArgument;

    constructor(message: string) {
      super('DlcError', 'InvalidArgument', message);
    }

    static instanceOf(e: any): e is InvalidArgument {
      return instanceOf(e) && (e as any)[variantOrdinalSymbol] === 5;
    }
  }
  class SerializationError extends UniffiError {
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [uniffiTypeNameSymbol]: string = 'DlcError';
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [variantOrdinalSymbol] = 6;

    readonly tag = DlcError_Tags.SerializationError;

    constructor(message: string) {
      super('DlcError', 'SerializationError', message);
    }

    static instanceOf(e: any): e is SerializationError {
      return instanceOf(e) && (e as any)[variantOrdinalSymbol] === 6;
    }
  }
  class Secp256k1Error extends UniffiError {
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [uniffiTypeNameSymbol]: string = 'DlcError';
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [variantOrdinalSymbol] = 7;

    readonly tag = DlcError_Tags.Secp256k1Error;

    constructor(message: string) {
      super('DlcError', 'Secp256k1Error', message);
    }

    static instanceOf(e: any): e is Secp256k1Error {
      return instanceOf(e) && (e as any)[variantOrdinalSymbol] === 7;
    }
  }
  class MiniscriptError extends UniffiError {
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [uniffiTypeNameSymbol]: string = 'DlcError';
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [variantOrdinalSymbol] = 8;

    readonly tag = DlcError_Tags.MiniscriptError;

    constructor(message: string) {
      super('DlcError', 'MiniscriptError', message);
    }

    static instanceOf(e: any): e is MiniscriptError {
      return instanceOf(e) && (e as any)[variantOrdinalSymbol] === 8;
    }
  }
  class InvalidNetwork extends UniffiError {
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [uniffiTypeNameSymbol]: string = 'DlcError';
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [variantOrdinalSymbol] = 9;

    readonly tag = DlcError_Tags.InvalidNetwork;

    constructor(message: string) {
      super('DlcError', 'InvalidNetwork', message);
    }

    static instanceOf(e: any): e is InvalidNetwork {
      return instanceOf(e) && (e as any)[variantOrdinalSymbol] === 9;
    }
  }
  class KeyError extends UniffiError {
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [uniffiTypeNameSymbol]: string = 'DlcError';
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [variantOrdinalSymbol] = 10;

    readonly tag = DlcError_Tags.KeyError;

    constructor(message: string) {
      super('DlcError', 'KeyError', message);
    }

    static instanceOf(e: any): e is KeyError {
      return instanceOf(e) && (e as any)[variantOrdinalSymbol] === 10;
    }
  }

  // Utility function which does not rely on instanceof.
  function instanceOf(e: any): e is DlcError {
    return (e as any)[uniffiTypeNameSymbol] === 'DlcError';
  }
  return {
    InvalidSignature,
    InvalidPublicKey,
    InvalidTransaction,
    InsufficientFunds,
    InvalidArgument,
    SerializationError,
    Secp256k1Error,
    MiniscriptError,
    InvalidNetwork,
    KeyError,
    instanceOf,
  };
})();

// Union type for DlcError error type.
export type DlcError = InstanceType<
  (typeof DlcError)[
    | 'InvalidSignature'
    | 'InvalidPublicKey'
    | 'InvalidTransaction'
    | 'InsufficientFunds'
    | 'InvalidArgument'
    | 'SerializationError'
    | 'Secp256k1Error'
    | 'MiniscriptError'
    | 'InvalidNetwork'
    | 'KeyError']
>;

const FfiConverterTypeDLCError = (() => {
  const intConverter = FfiConverterInt32;
  type TypeName = DlcError;
  class FfiConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      switch (intConverter.read(from)) {
        case 1:
          return new DlcError.InvalidSignature(FfiConverterString.read(from));

        case 2:
          return new DlcError.InvalidPublicKey(FfiConverterString.read(from));

        case 3:
          return new DlcError.InvalidTransaction(FfiConverterString.read(from));

        case 4:
          return new DlcError.InsufficientFunds(FfiConverterString.read(from));

        case 5:
          return new DlcError.InvalidArgument(FfiConverterString.read(from));

        case 6:
          return new DlcError.SerializationError(FfiConverterString.read(from));

        case 7:
          return new DlcError.Secp256k1Error(FfiConverterString.read(from));

        case 8:
          return new DlcError.MiniscriptError(FfiConverterString.read(from));

        case 9:
          return new DlcError.InvalidNetwork(FfiConverterString.read(from));

        case 10:
          return new DlcError.KeyError(FfiConverterString.read(from));

        default:
          throw new UniffiInternalError.UnexpectedEnumCase();
      }
    }
    write(value: TypeName, into: RustBuffer): void {
      const obj = value as any;
      const index = obj[variantOrdinalSymbol] as number;
      intConverter.write(index, into);
    }
    allocationSize(value: TypeName): number {
      return intConverter.allocationSize(0);
    }
  }
  return new FfiConverter();
})();

// Flat error type: ExtendedKey
export enum ExtendedKey_Tags {
  InvalidMnemonic = 'InvalidMnemonic',
  InvalidXpriv = 'InvalidXpriv',
  InvalidXpub = 'InvalidXpub',
  InvalidDerivationPath = 'InvalidDerivationPath',
}
export const ExtendedKey = (() => {
  class InvalidMnemonic extends UniffiError {
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [uniffiTypeNameSymbol]: string = 'ExtendedKey';
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [variantOrdinalSymbol] = 1;

    readonly tag = ExtendedKey_Tags.InvalidMnemonic;

    constructor(message: string) {
      super('ExtendedKey', 'InvalidMnemonic', message);
    }

    static instanceOf(e: any): e is InvalidMnemonic {
      return instanceOf(e) && (e as any)[variantOrdinalSymbol] === 1;
    }
  }
  class InvalidXpriv extends UniffiError {
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [uniffiTypeNameSymbol]: string = 'ExtendedKey';
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [variantOrdinalSymbol] = 2;

    readonly tag = ExtendedKey_Tags.InvalidXpriv;

    constructor(message: string) {
      super('ExtendedKey', 'InvalidXpriv', message);
    }

    static instanceOf(e: any): e is InvalidXpriv {
      return instanceOf(e) && (e as any)[variantOrdinalSymbol] === 2;
    }
  }
  class InvalidXpub extends UniffiError {
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [uniffiTypeNameSymbol]: string = 'ExtendedKey';
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [variantOrdinalSymbol] = 3;

    readonly tag = ExtendedKey_Tags.InvalidXpub;

    constructor(message: string) {
      super('ExtendedKey', 'InvalidXpub', message);
    }

    static instanceOf(e: any): e is InvalidXpub {
      return instanceOf(e) && (e as any)[variantOrdinalSymbol] === 3;
    }
  }
  class InvalidDerivationPath extends UniffiError {
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [uniffiTypeNameSymbol]: string = 'ExtendedKey';
    /**
     * @private
     * This field is private and should not be used.
     */
    readonly [variantOrdinalSymbol] = 4;

    readonly tag = ExtendedKey_Tags.InvalidDerivationPath;

    constructor(message: string) {
      super('ExtendedKey', 'InvalidDerivationPath', message);
    }

    static instanceOf(e: any): e is InvalidDerivationPath {
      return instanceOf(e) && (e as any)[variantOrdinalSymbol] === 4;
    }
  }

  // Utility function which does not rely on instanceof.
  function instanceOf(e: any): e is ExtendedKey {
    return (e as any)[uniffiTypeNameSymbol] === 'ExtendedKey';
  }
  return {
    InvalidMnemonic,
    InvalidXpriv,
    InvalidXpub,
    InvalidDerivationPath,
    instanceOf,
  };
})();

// Union type for ExtendedKey error type.
export type ExtendedKey = InstanceType<
  (typeof ExtendedKey)[
    | 'InvalidMnemonic'
    | 'InvalidXpriv'
    | 'InvalidXpub'
    | 'InvalidDerivationPath']
>;

const FfiConverterTypeExtendedKey = (() => {
  const intConverter = FfiConverterInt32;
  type TypeName = ExtendedKey;
  class FfiConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      switch (intConverter.read(from)) {
        case 1:
          return new ExtendedKey.InvalidMnemonic(FfiConverterString.read(from));

        case 2:
          return new ExtendedKey.InvalidXpriv(FfiConverterString.read(from));

        case 3:
          return new ExtendedKey.InvalidXpub(FfiConverterString.read(from));

        case 4:
          return new ExtendedKey.InvalidDerivationPath(
            FfiConverterString.read(from)
          );

        default:
          throw new UniffiInternalError.UnexpectedEnumCase();
      }
    }
    write(value: TypeName, into: RustBuffer): void {
      const obj = value as any;
      const index = obj[variantOrdinalSymbol] as number;
      intConverter.write(index, into);
    }
    allocationSize(value: TypeName): number {
      return intConverter.allocationSize(0);
    }
  }
  return new FfiConverter();
})();

// FfiConverter for Array<number>
const FfiConverterSequenceUInt8 = new FfiConverterArray(FfiConverterUInt8);

// FfiConverter for Array<Array<number>>
const FfiConverterSequenceSequenceUInt8 = new FfiConverterArray(
  FfiConverterSequenceUInt8
);

// FfiConverter for Array<TxInput>
const FfiConverterSequenceTypeTxInput = new FfiConverterArray(
  FfiConverterTypeTxInput
);

// FfiConverter for Array<TxOutput>
const FfiConverterSequenceTypeTxOutput = new FfiConverterArray(
  FfiConverterTypeTxOutput
);

// FfiConverter for Array<Transaction>
const FfiConverterSequenceTypeTransaction = new FfiConverterArray(
  FfiConverterTypeTransaction
);

// FfiConverter for Array<TxInputInfo>
const FfiConverterSequenceTypeTxInputInfo = new FfiConverterArray(
  FfiConverterTypeTxInputInfo
);

// FfiConverter for Array<DlcInputInfo>
const FfiConverterSequenceTypeDlcInputInfo = new FfiConverterArray(
  FfiConverterTypeDlcInputInfo
);

// FfiConverter for string | undefined
const FfiConverterOptionalString = new FfiConverterOptional(FfiConverterString);

// FfiConverter for Array<OracleInfo>
const FfiConverterSequenceTypeOracleInfo = new FfiConverterArray(
  FfiConverterTypeOracleInfo
);

// FfiConverter for Array<Array<Array<number>>>
const FfiConverterSequenceSequenceSequenceUInt8 = new FfiConverterArray(
  FfiConverterSequenceSequenceUInt8
);

// FfiConverter for Array<Array<Array<Array<number>>>>
const FfiConverterSequenceSequenceSequenceSequenceUInt8 = new FfiConverterArray(
  FfiConverterSequenceSequenceSequenceUInt8
);

// FfiConverter for Array<AdaptorSignature>
const FfiConverterSequenceTypeAdaptorSignature = new FfiConverterArray(
  FfiConverterTypeAdaptorSignature
);

// FfiConverter for Array<Payout>
const FfiConverterSequenceTypePayout = new FfiConverterArray(
  FfiConverterTypePayout
);

/**
 * This should be called before anything else.
 *
 * It is likely that this is being done for you by the library's `index.ts`.
 *
 * It checks versions of uniffi between when the Rust scaffolding was generated
 * and when the bindings were generated.
 *
 * It also initializes the machinery to enable Rust to talk back to Javascript.
 */
function uniffiEnsureInitialized() {
  // Get the bindings contract version from our ComponentInterface
  const bindingsContractVersion = 30;
  // Get the scaffolding contract version by calling the into the dylib
  const scaffoldingContractVersion =
    nativeModule().ubrn_ffi_ddk_ffi_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new UniffiInternalError.ContractVersionMismatch(
      scaffoldingContractVersion,
      bindingsContractVersion
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_add_signature_to_transaction() !==
    1337
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_add_signature_to_transaction'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_convert_mnemonic_to_seed() !==
    65049
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_convert_mnemonic_to_seed'
    );
  }
  if (nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_cet() !== 23081) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_cet'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_cet_adaptor_points_from_oracle_info() !==
    6552
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_cet_adaptor_points_from_oracle_info'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_cet_adaptor_signature_from_oracle_info() !==
    65174
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_cet_adaptor_signature_from_oracle_info'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_cet_adaptor_sigs_from_oracle_info() !==
    15699
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_cet_adaptor_sigs_from_oracle_info'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_cet_adaptor_sigs_from_points() !==
    33705
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_cet_adaptor_sigs_from_points'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_cets() !== 50529
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_cets'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_dlc_transactions() !==
    29518
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_dlc_transactions'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_extkey_from_parent_path() !==
    26671
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_extkey_from_parent_path'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_extkey_from_seed() !==
    12526
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_extkey_from_seed'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_fund_tx_locking_script() !==
    2761
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_fund_tx_locking_script'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_refund_transaction() !==
    57261
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_refund_transaction'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_spliced_dlc_transactions() !==
    19497
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_spliced_dlc_transactions'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_xpriv_from_parent_path() !==
    34808
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_xpriv_from_parent_path'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_extract_ecdsa_signature_from_oracle_signatures() !==
    8006
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_extract_ecdsa_signature_from_oracle_signatures'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_get_cet_adaptor_signature_inputs() !==
    14595
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_get_cet_adaptor_signature_inputs'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_get_cet_sighash() !== 10643
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_get_cet_sighash'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_get_change_output_and_fees() !==
    44150
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_get_change_output_and_fees'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_get_pubkey_from_extkey() !==
    64637
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_get_pubkey_from_extkey'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_get_raw_funding_transaction_input_signature() !==
    35708
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_get_raw_funding_transaction_input_signature'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_get_total_input_vsize() !==
    38213
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_get_total_input_vsize'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_get_xpub_from_xpriv() !==
    44344
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_get_xpub_from_xpriv'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_is_dust_output() !== 64174
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_is_dust_output'
    );
  }
  if (nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_sign_cet() !== 43957) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_sign_cet'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_sign_fund_transaction_input() !==
    50531
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_sign_fund_transaction_input'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_sign_multi_sig_input() !==
    14569
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_sign_multi_sig_input'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_verify_cet_adaptor_sig_from_oracle_info() !==
    52232
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_verify_cet_adaptor_sig_from_oracle_info'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_verify_cet_adaptor_sigs_from_oracle_info() !==
    14181
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_verify_cet_adaptor_sigs_from_oracle_info'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_verify_fund_tx_signature() !==
    27316
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_verify_fund_tx_signature'
    );
  }
  if (nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_version() !== 22317) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_version'
    );
  }
}

export default Object.freeze({
  initialize: uniffiEnsureInitialized,
  converters: {
    FfiConverterTypeAdaptorSignature,
    FfiConverterTypeCetAdaptorSignatureDebugInfo,
    FfiConverterTypeChangeOutputAndFees,
    FfiConverterTypeDLCError,
    FfiConverterTypeDlcInputInfo,
    FfiConverterTypeDlcTransactions,
    FfiConverterTypeExtendedKey,
    FfiConverterTypeOracleInfo,
    FfiConverterTypePartyParams,
    FfiConverterTypePayout,
    FfiConverterTypeTransaction,
    FfiConverterTypeTxInput,
    FfiConverterTypeTxInputInfo,
    FfiConverterTypeTxOutput,
  },
});
