// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import nativeModule from './ddk_ffi-ffi';
import {
  type UniffiRustFutureContinuationCallback,
  type UniffiForeignFutureDroppedCallback,
  type UniffiForeignFutureDroppedCallbackStruct,
} from './ddk_ffi-ffi';
import {
  type UniffiByteArray,
  AbstractFfiConverterByteArray,
  FfiConverterArray,
  FfiConverterArrayBuffer,
  FfiConverterBool,
  FfiConverterInt32,
  FfiConverterOptional,
  FfiConverterUInt32,
  FfiConverterUInt64,
  FfiConverterUInt8,
  RustBuffer,
  UniffiEnum,
  UniffiError,
  UniffiInternalError,
  UniffiRustCaller,
  uniffiCreateFfiConverterString,
  uniffiCreateRecord,
  uniffiTypeNameSymbol,
  variantOrdinalSymbol,
} from '@ubjs/core';
const uniffiCaller = new UniffiRustCaller(() => ({ code: 0 }));

const uniffiIsDebug =
  // @ts-ignore -- The process global might not be defined
  typeof process !== 'object' ||
  // @ts-ignore -- The process global might not be defined
  process?.env?.NODE_ENV !== 'production' ||
  false;

// Public interface members begin here.

export function convertMnemonicToSeed(
  mnemonic: string,
  passphrase: string | undefined
): ArrayBuffer /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterArrayBuffer.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_convert_mnemonic_to_seed(
          FfiConverterString.lower(mnemonic, nativeModule().rustbuffer_alloc),
          FfiConverterOptionalString.lower(
            passphrase,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

/**
 * Create a single CET
 */
export function createCet(
  localOutput: TxOutput,
  localPayoutSerialId: bigint,
  remoteOutput: TxOutput,
  remotePayoutSerialId: bigint,
  fundTxId: string,
  fundVout: number,
  lockTime: number
): Transaction /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeTransaction.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_create_cet(
          FfiConverterTypeTxOutput.lower(
            localOutput,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            localPayoutSerialId,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterTypeTxOutput.lower(
            remoteOutput,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            remotePayoutSerialId,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(fundTxId, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(fundVout, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(lockTime, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createCetAdaptorPointsFromOracleInfo(
  oracleInfo: Array<OracleInfo>,
  msgs: Array<Array<Array<ArrayBuffer>>>
): Array<ArrayBuffer> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceBytes.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_points_from_oracle_info(
          FfiConverterSequenceTypeOracleInfo.lower(
            oracleInfo,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceSequenceSequenceBytes.lower(
            msgs,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function createCetAdaptorSigsFromOracleInfo(
  cets: Array<Transaction>,
  oracleInfo: Array<OracleInfo>,
  fundingSecretKey: ArrayBuffer,
  fundingScriptPubkey: ArrayBuffer,
  fundOutputValue: bigint,
  msgs: Array<Array<Array<ArrayBuffer>>>
): Array<AdaptorSignature> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceTypeAdaptorSignature.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_sigs_from_oracle_info(
          FfiConverterSequenceTypeTransaction.lower(
            cets,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceTypeOracleInfo.lower(
            oracleInfo,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterArrayBuffer.lower(
            fundingSecretKey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterArrayBuffer.lower(
            fundingScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            fundOutputValue,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceSequenceSequenceBytes.lower(
            msgs,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

/**
 * Create adaptor signatures from pre-computed adaptor points.
 */
export function createCetAdaptorSigsFromPoints(
  cets: Array<Transaction>,
  adaptorPoints: Array<ArrayBuffer>,
  fundingSecretKey: ArrayBuffer,
  fundingScriptPubkey: ArrayBuffer,
  fundOutputValue: bigint
): Array<AdaptorSignature> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceTypeAdaptorSignature.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_create_cet_adaptor_sigs_from_points(
          FfiConverterSequenceTypeTransaction.lower(
            cets,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceBytes.lower(
            adaptorPoints,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterArrayBuffer.lower(
            fundingSecretKey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterArrayBuffer.lower(
            fundingScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            fundOutputValue,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

/**
 * Create multiple CETs
 */
export function createCets(
  fundTxId: string,
  fundVout: number,
  localFinalScriptPubkey: ArrayBuffer,
  remoteFinalScriptPubkey: ArrayBuffer,
  outcomes: Array<Payout>,
  lockTime: number,
  localSerialId: bigint,
  remoteSerialId: bigint
): Array<Transaction> /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterSequenceTypeTransaction.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_create_cets(
          FfiConverterString.lower(fundTxId, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(fundVout, nativeModule().rustbuffer_alloc),
          FfiConverterArrayBuffer.lower(
            localFinalScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterArrayBuffer.lower(
            remoteFinalScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceTypePayout.lower(
            outcomes,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt32.lower(lockTime, nativeModule().rustbuffer_alloc),
          FfiConverterUInt64.lower(
            localSerialId,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            remoteSerialId,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

/**
 * Create complete DLC transactions
 */
export function createDlcTransactions(
  outcomes: Array<Payout>,
  localParams: PartyParams,
  remoteParams: PartyParams,
  refundLocktime: number,
  feeRate: bigint,
  fundLockTime: number,
  cetLockTime: number,
  fundOutputSerialId: bigint
): DlcTransactions /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeDlcTransactions.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_create_dlc_transactions(
          FfiConverterSequenceTypePayout.lower(
            outcomes,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterTypePartyParams.lower(
            localParams,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterTypePartyParams.lower(
            remoteParams,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt32.lower(
            refundLocktime,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(feeRate, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(
            fundLockTime,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt32.lower(
            cetLockTime,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            fundOutputSerialId,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

/**
 * Derive child extended private key from parent extended key
 * Input: 78-byte encoded xpriv, Output: 78-byte encoded xpriv
 */
export function createExtkeyFromParentPath(
  extkey: ArrayBuffer,
  path: string
): ArrayBuffer /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterArrayBuffer.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_create_extkey_from_parent_path(
          FfiConverterArrayBuffer.lower(
            extkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(path, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

/**
 * Create master extended private key from 64-byte seed
 * Returns 78-byte encoded xpriv
 */
export function createExtkeyFromSeed(
  seed: ArrayBuffer,
  network: string
): ArrayBuffer /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterArrayBuffer.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_create_extkey_from_seed(
          FfiConverterArrayBuffer.lower(seed, nativeModule().rustbuffer_alloc),
          FfiConverterString.lower(network, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

/**
 * Create a funding script pubkey for DLC transactions
 */
export function createFundTxLockingScript(
  localFundPubkey: ArrayBuffer,
  remoteFundPubkey: ArrayBuffer
): ArrayBuffer /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterArrayBuffer.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_create_fund_tx_locking_script(
          FfiConverterArrayBuffer.lower(
            localFundPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterArrayBuffer.lower(
            remoteFundPubkey,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

/**
 * Create a refund transaction
 */
export function createRefundTransaction(
  localFinalScriptPubkey: ArrayBuffer,
  remoteFinalScriptPubkey: ArrayBuffer,
  localAmount: bigint,
  remoteAmount: bigint,
  lockTime: number,
  fundTxId: string,
  fundVout: number
): Transaction /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeTransaction.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_create_refund_transaction(
          FfiConverterArrayBuffer.lower(
            localFinalScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterArrayBuffer.lower(
            remoteFinalScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            localAmount,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            remoteAmount,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt32.lower(lockTime, nativeModule().rustbuffer_alloc),
          FfiConverterString.lower(fundTxId, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(fundVout, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

/**
 * Create spliced DLC transactions
 */
export function createSplicedDlcTransactions(
  outcomes: Array<Payout>,
  localParams: PartyParams,
  remoteParams: PartyParams,
  refundLocktime: number,
  feeRate: bigint,
  fundLockTime: number,
  cetLockTime: number,
  fundOutputSerialId: bigint
): DlcTransactions /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterTypeDlcTransactions.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_create_spliced_dlc_transactions(
          FfiConverterSequenceTypePayout.lower(
            outcomes,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterTypePartyParams.lower(
            localParams,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterTypePartyParams.lower(
            remoteParams,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt32.lower(
            refundLocktime,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(feeRate, nativeModule().rustbuffer_alloc),
          FfiConverterUInt32.lower(
            fundLockTime,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt32.lower(
            cetLockTime,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            fundOutputSerialId,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

/**
 * DEPRECATED: Use create_extkey_from_seed + create_extkey_from_parent_path instead
 * This function handles both seeds (64 bytes) and xprivs (78 bytes) which is confusing
 */
export function createXprivFromParentPath(
  seedOrXpriv: ArrayBuffer,
  baseDerivationPath: string,
  network: string,
  path: string
): ArrayBuffer /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterArrayBuffer.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_create_xpriv_from_parent_path(
          FfiConverterArrayBuffer.lower(
            seedOrXpriv,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(
            baseDerivationPath,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(network, nativeModule().rustbuffer_alloc),
          FfiConverterString.lower(path, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function extractEcdsaSignatureFromOracleSignatures(
  oracleSignatures: Array<ArrayBuffer>,
  adaptorSignature: ArrayBuffer
): ArrayBuffer /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterArrayBuffer.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_extract_ecdsa_signature_from_oracle_signatures(
          FfiConverterSequenceBytes.lower(
            oracleSignatures,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterArrayBuffer.lower(
            adaptorSignature,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

/**
 * Extract public key from extended key (private or public)
 * Input: 78-byte encoded xpriv/xpub, Output: 33-byte compressed public key
 */
export function getPubkeyFromExtkey(
  extkey: ArrayBuffer,
  network: string
): ArrayBuffer /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterArrayBuffer.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_get_pubkey_from_extkey(
          FfiConverterArrayBuffer.lower(
            extkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterString.lower(network, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

/**
 * Get total input virtual size for fee calculation
 */
export function getTotalInputVsize(inputs: Array<TxInputInfo>): number {
  return FfiConverterUInt32.lift(
    uniffiCaller.rustCall(
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_get_total_input_vsize(
          FfiConverterSequenceTypeTxInputInfo.lower(
            inputs,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

/**
 * Convert extended private key to extended public key
 * Input: 78-byte encoded xpriv, Output: 78-byte encoded xpub
 */
export function getXpubFromXpriv(
  xpriv: ArrayBuffer,
  network: string
): ArrayBuffer /*throws*/ {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterArrayBuffer.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCallWithError(
      /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
        FfiConverterTypeDLCError
      ),
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_get_xpub_from_xpriv(
          FfiConverterArrayBuffer.lower(xpriv, nativeModule().rustbuffer_alloc),
          FfiConverterString.lower(network, nativeModule().rustbuffer_alloc),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function verifyCetAdaptorSigsFromOracleInfo(
  adaptorSigs: Array<AdaptorSignature>,
  cets: Array<Transaction>,
  oracleInfos: Array<OracleInfo>,
  pubkey: ArrayBuffer,
  fundingScriptPubkey: ArrayBuffer,
  totalCollateral: bigint,
  msgs: Array<Array<Array<ArrayBuffer>>>
): boolean {
  return FfiConverterBool.lift(
    uniffiCaller.rustCall(
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_verify_cet_adaptor_sigs_from_oracle_info(
          FfiConverterSequenceTypeAdaptorSignature.lower(
            adaptorSigs,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceTypeTransaction.lower(
            cets,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceTypeOracleInfo.lower(
            oracleInfos,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterArrayBuffer.lower(
            pubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterArrayBuffer.lower(
            fundingScriptPubkey,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterUInt64.lower(
            totalCollateral,
            nativeModule().rustbuffer_alloc
          ),
          FfiConverterSequenceSequenceSequenceBytes.lower(
            msgs,
            nativeModule().rustbuffer_alloc
          ),
          callStatus
        );
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export function version(): string {
  return ((__rb: Uint8Array) => {
    try {
      return FfiConverterString.lift(__rb);
    } finally {
      nativeModule().rustbuffer_free(__rb);
    }
  })(
    uniffiCaller.rustCall(
      /*caller:*/ (callStatus) => {
        return nativeModule().ubrn_uniffi_ddk_ffi_fn_func_version(callStatus);
      },
      /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
    )
  );
}

export type AdaptorSignature = {
  signature: ArrayBuffer;
  proof: ArrayBuffer;
};

/**
 * Generated factory for {@link AdaptorSignature} record objects.
 */
export const AdaptorSignature = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<AdaptorSignature, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<AdaptorSignature>,
    verifyFromOracleInfo(
      self_: AdaptorSignature,
      cet: Transaction,
      oracleInfos: Array<OracleInfo>,
      pubkey: ArrayBuffer,
      fundingScriptPubkey: ArrayBuffer,
      totalCollateral: bigint,
      msgs: Array<Array<ArrayBuffer>>
    ): boolean {
      return FfiConverterBool.lift(
        uniffiCaller.rustCall(
          /*caller:*/ (callStatus) => {
            return nativeModule().ubrn_uniffi_ddk_ffi_fn_method_adaptorsignature_verify_from_oracle_info(
              FfiConverterTypeAdaptorSignature.lower(
                self_,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterTypeTransaction.lower(
                cet,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterSequenceTypeOracleInfo.lower(
                oracleInfos,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                pubkey,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                fundingScriptPubkey,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterUInt64.lower(
                totalCollateral,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterSequenceSequenceBytes.lower(
                msgs,
                nativeModule().rustbuffer_alloc
              ),
              callStatus
            );
          },
          /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
        )
      );
    },
  });
})();

const FfiConverterTypeAdaptorSignature = (() => {
  type TypeName = AdaptorSignature;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        signature: FfiConverterArrayBuffer.read(from),
        proof: FfiConverterArrayBuffer.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterArrayBuffer.write(value.signature, into);
      FfiConverterArrayBuffer.write(value.proof, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterArrayBuffer.allocationSize(value.signature) +
        FfiConverterArrayBuffer.allocationSize(value.proof)
      );
    }
  }
  return new FFIConverter();
})();

// Hermes (React Native ≥ 0.74) ships TextEncoder and encodeInto, but not
// TextDecoder. For single-string decode (bytesToString), we polyfill via the
// C++ string_from_buffer helper using a duck-typed object matching the
// standard TextDecoder.decode signature. Once Hermes ships a real
// TextDecoder, the `typeof` check will pick it up automatically.
//
// For array-of-strings decode (readStringFromBuffer), we keep a dedicated C++
// helper: the polyfill path (new Uint8Array view + decode) measured ~40%
// slower on getStringArray benchmarks than a direct (buf, offset, length)
// call, due to the per-read view allocation and extra property lookups in
// string_from_buffer.
const stringConverter = (() => {
  const encoder = new TextEncoder();
  const decoder: { decode(input: UniffiByteArray): string } =
    typeof TextDecoder !== 'undefined'
      ? new TextDecoder()
      : {
          decode: (bytes: UniffiByteArray) =>
            nativeModule().ubrn_uniffi_internal_fn_func_ffi__string_from_buffer(
              bytes,
              undefined as any
            ) as string,
        };
  return {
    // Single-string lower() uses the C++ helper — TextEncoder.encode
    // measured ~43% slower on takeString benchmarks.
    stringToBytes: (s: string) =>
      nativeModule().ubrn_uniffi_internal_fn_func_ffi__string_to_buffer(
        s,
        undefined as any
      ),
    bytesToString: (ab: UniffiByteArray) => decoder.decode(ab),
    // Direct C++ call — bypasses uniffiCaller.rustCall() overhead.
    // Matters for N-element arrays.
    stringByteLength: (s: string) =>
      nativeModule().ubrn_uniffi_internal_fn_func_ffi__string_to_byte_length(
        s,
        undefined as any
      ) as number,
    // Encode directly into the RustBuffer backing store via
    // TextEncoder.encodeInto — zero intermediate allocation. Replaces
    // the old C++ write_string_into_buffer helper.
    writeStringIntoBuffer: (s: string, buf: any, offset: number): number => {
      const view = new Uint8Array(
        buf.arrayBuffer,
        offset,
        buf.arrayBuffer.byteLength - offset
      );
      return encoder.encodeInto(s, view).written;
    },
    // Dedicated C++ helper — avoids per-read Uint8Array allocation and
    // the double property-lookup in string_from_buffer.
    readStringFromBuffer: (buf: any, offset: number, length: number): string =>
      nativeModule().ubrn_uniffi_internal_fn_func_ffi__read_string_from_buffer(
        buf,
        offset,
        length
      ) as string,
  };
})();
const FfiConverterString = uniffiCreateFfiConverterString(stringConverter);

/**
 * Debug info for CET adaptor signature inputs.
 *
 * Contains all the values that go into creating an adaptor signature,
 * useful for comparing with external signers during debugging.
 *
 * This struct is intentionally always available (not feature-gated)
 * to support production debugging scenarios.
 */
export type CetAdaptorSignatureDebugInfo = {
  /**
   * The sighash (32 bytes) - this is the message that gets signed
   */
  sighash: ArrayBuffer;
  /**
   * The adaptor point (33 bytes compressed public key)
   */
  adaptorPoint: ArrayBuffer;
  /**
   * Input index (always 0 for CETs)
   */
  inputIndex: number;
  /**
   * The funding script pubkey used for sighash
   */
  scriptPubkey: ArrayBuffer;
  /**
   * The fund output value used for sighash
   */
  value: bigint;
  /**
   * The CET txid
   */
  cetTxid: string;
  /**
   * Raw CET bytes for verification
   */
  cetRaw: ArrayBuffer;
};

/**
 * Generated factory for {@link CetAdaptorSignatureDebugInfo} record objects.
 */
export const CetAdaptorSignatureDebugInfo = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<
      CetAdaptorSignatureDebugInfo,
      ReturnType<typeof defaults>
    >(defaults);
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () =>
      Object.freeze(defaults()) as Partial<CetAdaptorSignatureDebugInfo>,
  });
})();

const FfiConverterTypeCetAdaptorSignatureDebugInfo = (() => {
  type TypeName = CetAdaptorSignatureDebugInfo;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        sighash: FfiConverterArrayBuffer.read(from),
        adaptorPoint: FfiConverterArrayBuffer.read(from),
        inputIndex: FfiConverterUInt32.read(from),
        scriptPubkey: FfiConverterArrayBuffer.read(from),
        value: FfiConverterUInt64.read(from),
        cetTxid: FfiConverterString.read(from),
        cetRaw: FfiConverterArrayBuffer.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterArrayBuffer.write(value.sighash, into);
      FfiConverterArrayBuffer.write(value.adaptorPoint, into);
      FfiConverterUInt32.write(value.inputIndex, into);
      FfiConverterArrayBuffer.write(value.scriptPubkey, into);
      FfiConverterUInt64.write(value.value, into);
      FfiConverterString.write(value.cetTxid, into);
      FfiConverterArrayBuffer.write(value.cetRaw, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterArrayBuffer.allocationSize(value.sighash) +
        FfiConverterArrayBuffer.allocationSize(value.adaptorPoint) +
        FfiConverterUInt32.allocationSize(value.inputIndex) +
        FfiConverterArrayBuffer.allocationSize(value.scriptPubkey) +
        FfiConverterUInt64.allocationSize(value.value) +
        FfiConverterString.allocationSize(value.cetTxid) +
        FfiConverterArrayBuffer.allocationSize(value.cetRaw)
      );
    }
  }
  return new FFIConverter();
})();

export type TxOutput = {
  value: bigint;
  scriptPubkey: ArrayBuffer;
};

/**
 * Generated factory for {@link TxOutput} record objects.
 */
export const TxOutput = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<TxOutput, ReturnType<typeof defaults>>(defaults);
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<TxOutput>,
    isDust(self_: TxOutput): boolean {
      return FfiConverterBool.lift(
        uniffiCaller.rustCall(
          /*caller:*/ (callStatus) => {
            return nativeModule().ubrn_uniffi_ddk_ffi_fn_method_txoutput_is_dust(
              FfiConverterTypeTxOutput.lower(
                self_,
                nativeModule().rustbuffer_alloc
              ),
              callStatus
            );
          },
          /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
        )
      );
    },
  });
})();

const FfiConverterTypeTxOutput = (() => {
  type TypeName = TxOutput;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        value: FfiConverterUInt64.read(from),
        scriptPubkey: FfiConverterArrayBuffer.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterUInt64.write(value.value, into);
      FfiConverterArrayBuffer.write(value.scriptPubkey, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterUInt64.allocationSize(value.value) +
        FfiConverterArrayBuffer.allocationSize(value.scriptPubkey)
      );
    }
  }
  return new FFIConverter();
})();

export type ChangeOutputAndFees = {
  changeOutput: TxOutput;
  fundFee: bigint;
  cetFee: bigint;
};

/**
 * Generated factory for {@link ChangeOutputAndFees} record objects.
 */
export const ChangeOutputAndFees = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<ChangeOutputAndFees, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<ChangeOutputAndFees>,
  });
})();

const FfiConverterTypeChangeOutputAndFees = (() => {
  type TypeName = ChangeOutputAndFees;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        changeOutput: FfiConverterTypeTxOutput.read(from),
        fundFee: FfiConverterUInt64.read(from),
        cetFee: FfiConverterUInt64.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterTypeTxOutput.write(value.changeOutput, into);
      FfiConverterUInt64.write(value.fundFee, into);
      FfiConverterUInt64.write(value.cetFee, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterTypeTxOutput.allocationSize(value.changeOutput) +
        FfiConverterUInt64.allocationSize(value.fundFee) +
        FfiConverterUInt64.allocationSize(value.cetFee)
      );
    }
  }
  return new FFIConverter();
})();

export type TxInput = {
  txid: string;
  vout: number;
  scriptSig: ArrayBuffer;
  sequence: number;
  witness: Array<ArrayBuffer>;
};

/**
 * Generated factory for {@link TxInput} record objects.
 */
export const TxInput = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<TxInput, ReturnType<typeof defaults>>(defaults);
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<TxInput>,
  });
})();

const FfiConverterTypeTxInput = (() => {
  type TypeName = TxInput;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        txid: FfiConverterString.read(from),
        vout: FfiConverterUInt32.read(from),
        scriptSig: FfiConverterArrayBuffer.read(from),
        sequence: FfiConverterUInt32.read(from),
        witness: FfiConverterSequenceBytes.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterString.write(value.txid, into);
      FfiConverterUInt32.write(value.vout, into);
      FfiConverterArrayBuffer.write(value.scriptSig, into);
      FfiConverterUInt32.write(value.sequence, into);
      FfiConverterSequenceBytes.write(value.witness, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterString.allocationSize(value.txid) +
        FfiConverterUInt32.allocationSize(value.vout) +
        FfiConverterArrayBuffer.allocationSize(value.scriptSig) +
        FfiConverterUInt32.allocationSize(value.sequence) +
        FfiConverterSequenceBytes.allocationSize(value.witness)
      );
    }
  }
  return new FFIConverter();
})();

export type Transaction = {
  version: number;
  lockTime: number;
  inputs: Array<TxInput>;
  outputs: Array<TxOutput>;
  rawBytes: ArrayBuffer;
};

/**
 * Generated factory for {@link Transaction} record objects.
 */
export const Transaction = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<Transaction, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<Transaction>,
    addSignature(
      self_: Transaction,
      signature: ArrayBuffer,
      pubkey: ArrayBuffer,
      inputIndex: number
    ): Transaction {
      return ((__rb: Uint8Array) => {
        try {
          return FfiConverterTypeTransaction.lift(__rb);
        } finally {
          nativeModule().rustbuffer_free(__rb);
        }
      })(
        uniffiCaller.rustCallWithError(
          /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
            FfiConverterTypeDLCError
          ),
          /*caller:*/ (callStatus) => {
            return nativeModule().ubrn_uniffi_ddk_ffi_fn_method_transaction_add_signature(
              FfiConverterTypeTransaction.lower(
                self_,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                signature,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                pubkey,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterUInt32.lower(
                inputIndex,
                nativeModule().rustbuffer_alloc
              ),
              callStatus
            );
          },
          /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
        )
      );
    },
    cetAdaptorSignatureFromOracleInfo(
      self_: Transaction,
      oracleInfo: OracleInfo,
      fundingSk: ArrayBuffer,
      fundingScriptPubkey: ArrayBuffer,
      totalCollateral: bigint,
      msgs: Array<ArrayBuffer>
    ): AdaptorSignature {
      return ((__rb: Uint8Array) => {
        try {
          return FfiConverterTypeAdaptorSignature.lift(__rb);
        } finally {
          nativeModule().rustbuffer_free(__rb);
        }
      })(
        uniffiCaller.rustCallWithError(
          /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
            FfiConverterTypeDLCError
          ),
          /*caller:*/ (callStatus) => {
            return nativeModule().ubrn_uniffi_ddk_ffi_fn_method_transaction_cet_adaptor_signature_from_oracle_info(
              FfiConverterTypeTransaction.lower(
                self_,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterTypeOracleInfo.lower(
                oracleInfo,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                fundingSk,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                fundingScriptPubkey,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterUInt64.lower(
                totalCollateral,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterSequenceBytes.lower(
                msgs,
                nativeModule().rustbuffer_alloc
              ),
              callStatus
            );
          },
          /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
        )
      );
    },
    cetAdaptorSignatureInputs(
      self_: Transaction,
      oracleInfo: Array<OracleInfo>,
      fundingScriptPubkey: ArrayBuffer,
      fundOutputValue: bigint,
      msgs: Array<Array<ArrayBuffer>>
    ): CetAdaptorSignatureDebugInfo {
      return ((__rb: Uint8Array) => {
        try {
          return FfiConverterTypeCetAdaptorSignatureDebugInfo.lift(__rb);
        } finally {
          nativeModule().rustbuffer_free(__rb);
        }
      })(
        uniffiCaller.rustCallWithError(
          /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
            FfiConverterTypeDLCError
          ),
          /*caller:*/ (callStatus) => {
            return nativeModule().ubrn_uniffi_ddk_ffi_fn_method_transaction_cet_adaptor_signature_inputs(
              FfiConverterTypeTransaction.lower(
                self_,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterSequenceTypeOracleInfo.lower(
                oracleInfo,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                fundingScriptPubkey,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterUInt64.lower(
                fundOutputValue,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterSequenceSequenceBytes.lower(
                msgs,
                nativeModule().rustbuffer_alloc
              ),
              callStatus
            );
          },
          /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
        )
      );
    },
    cetSighash(
      self_: Transaction,
      fundingScriptPubkey: ArrayBuffer,
      fundOutputValue: bigint
    ): ArrayBuffer {
      return ((__rb: Uint8Array) => {
        try {
          return FfiConverterArrayBuffer.lift(__rb);
        } finally {
          nativeModule().rustbuffer_free(__rb);
        }
      })(
        uniffiCaller.rustCallWithError(
          /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
            FfiConverterTypeDLCError
          ),
          /*caller:*/ (callStatus) => {
            return nativeModule().ubrn_uniffi_ddk_ffi_fn_method_transaction_cet_sighash(
              FfiConverterTypeTransaction.lower(
                self_,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                fundingScriptPubkey,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterUInt64.lower(
                fundOutputValue,
                nativeModule().rustbuffer_alloc
              ),
              callStatus
            );
          },
          /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
        )
      );
    },
    rawFundingInputSignature(
      self_: Transaction,
      privkey: ArrayBuffer,
      prevTxId: string,
      prevTxVout: number,
      value: bigint
    ): ArrayBuffer {
      return ((__rb: Uint8Array) => {
        try {
          return FfiConverterArrayBuffer.lift(__rb);
        } finally {
          nativeModule().rustbuffer_free(__rb);
        }
      })(
        uniffiCaller.rustCallWithError(
          /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
            FfiConverterTypeDLCError
          ),
          /*caller:*/ (callStatus) => {
            return nativeModule().ubrn_uniffi_ddk_ffi_fn_method_transaction_raw_funding_input_signature(
              FfiConverterTypeTransaction.lower(
                self_,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                privkey,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterString.lower(
                prevTxId,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterUInt32.lower(
                prevTxVout,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterUInt64.lower(value, nativeModule().rustbuffer_alloc),
              callStatus
            );
          },
          /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
        )
      );
    },
    signCet(
      self_: Transaction,
      adaptorSignature: ArrayBuffer,
      oracleSignatures: Array<ArrayBuffer>,
      fundingSecretKey: ArrayBuffer,
      otherPubkey: ArrayBuffer,
      fundingScriptPubkey: ArrayBuffer,
      fundOutputValue: bigint
    ): Transaction {
      return ((__rb: Uint8Array) => {
        try {
          return FfiConverterTypeTransaction.lift(__rb);
        } finally {
          nativeModule().rustbuffer_free(__rb);
        }
      })(
        uniffiCaller.rustCallWithError(
          /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
            FfiConverterTypeDLCError
          ),
          /*caller:*/ (callStatus) => {
            return nativeModule().ubrn_uniffi_ddk_ffi_fn_method_transaction_sign_cet(
              FfiConverterTypeTransaction.lower(
                self_,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                adaptorSignature,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterSequenceBytes.lower(
                oracleSignatures,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                fundingSecretKey,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                otherPubkey,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                fundingScriptPubkey,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterUInt64.lower(
                fundOutputValue,
                nativeModule().rustbuffer_alloc
              ),
              callStatus
            );
          },
          /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
        )
      );
    },
    signFundInput(
      self_: Transaction,
      privkey: ArrayBuffer,
      prevTxId: string,
      prevTxVout: number,
      value: bigint
    ): Transaction {
      return ((__rb: Uint8Array) => {
        try {
          return FfiConverterTypeTransaction.lift(__rb);
        } finally {
          nativeModule().rustbuffer_free(__rb);
        }
      })(
        uniffiCaller.rustCallWithError(
          /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
            FfiConverterTypeDLCError
          ),
          /*caller:*/ (callStatus) => {
            return nativeModule().ubrn_uniffi_ddk_ffi_fn_method_transaction_sign_fund_input(
              FfiConverterTypeTransaction.lower(
                self_,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                privkey,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterString.lower(
                prevTxId,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterUInt32.lower(
                prevTxVout,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterUInt64.lower(value, nativeModule().rustbuffer_alloc),
              callStatus
            );
          },
          /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
        )
      );
    },
    signMultiSigInput(
      self_: Transaction,
      dlcInput: DlcInputInfo,
      localPrivkey: ArrayBuffer,
      remoteSignature: ArrayBuffer
    ): Transaction {
      return ((__rb: Uint8Array) => {
        try {
          return FfiConverterTypeTransaction.lift(__rb);
        } finally {
          nativeModule().rustbuffer_free(__rb);
        }
      })(
        uniffiCaller.rustCallWithError(
          /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
            FfiConverterTypeDLCError
          ),
          /*caller:*/ (callStatus) => {
            return nativeModule().ubrn_uniffi_ddk_ffi_fn_method_transaction_sign_multi_sig_input(
              FfiConverterTypeTransaction.lower(
                self_,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterTypeDlcInputInfo.lower(
                dlcInput,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                localPrivkey,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                remoteSignature,
                nativeModule().rustbuffer_alloc
              ),
              callStatus
            );
          },
          /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
        )
      );
    },
    verifyFundSignature(
      self_: Transaction,
      signature: ArrayBuffer,
      pubkey: ArrayBuffer,
      txid: string,
      vout: number,
      inputAmount: bigint
    ): boolean {
      return FfiConverterBool.lift(
        uniffiCaller.rustCallWithError(
          /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
            FfiConverterTypeDLCError
          ),
          /*caller:*/ (callStatus) => {
            return nativeModule().ubrn_uniffi_ddk_ffi_fn_method_transaction_verify_fund_signature(
              FfiConverterTypeTransaction.lower(
                self_,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                signature,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterArrayBuffer.lower(
                pubkey,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterString.lower(txid, nativeModule().rustbuffer_alloc),
              FfiConverterUInt32.lower(vout, nativeModule().rustbuffer_alloc),
              FfiConverterUInt64.lower(
                inputAmount,
                nativeModule().rustbuffer_alloc
              ),
              callStatus
            );
          },
          /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
        )
      );
    },
  });
})();

const FfiConverterTypeTransaction = (() => {
  type TypeName = Transaction;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        version: FfiConverterInt32.read(from),
        lockTime: FfiConverterUInt32.read(from),
        inputs: FfiConverterSequenceTypeTxInput.read(from),
        outputs: FfiConverterSequenceTypeTxOutput.read(from),
        rawBytes: FfiConverterArrayBuffer.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterInt32.write(value.version, into);
      FfiConverterUInt32.write(value.lockTime, into);
      FfiConverterSequenceTypeTxInput.write(value.inputs, into);
      FfiConverterSequenceTypeTxOutput.write(value.outputs, into);
      FfiConverterArrayBuffer.write(value.rawBytes, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterInt32.allocationSize(value.version) +
        FfiConverterUInt32.allocationSize(value.lockTime) +
        FfiConverterSequenceTypeTxInput.allocationSize(value.inputs) +
        FfiConverterSequenceTypeTxOutput.allocationSize(value.outputs) +
        FfiConverterArrayBuffer.allocationSize(value.rawBytes)
      );
    }
  }
  return new FFIConverter();
})();

export type DlcInputInfo = {
  fundTx: Transaction;
  fundVout: number;
  localFundPubkey: ArrayBuffer;
  remoteFundPubkey: ArrayBuffer;
  fundAmount: bigint;
  maxWitnessLen: number;
  inputSerialId: bigint;
  contractId: ArrayBuffer;
};

/**
 * Generated factory for {@link DlcInputInfo} record objects.
 */
export const DlcInputInfo = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<DlcInputInfo, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<DlcInputInfo>,
  });
})();

const FfiConverterTypeDlcInputInfo = (() => {
  type TypeName = DlcInputInfo;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        fundTx: FfiConverterTypeTransaction.read(from),
        fundVout: FfiConverterUInt32.read(from),
        localFundPubkey: FfiConverterArrayBuffer.read(from),
        remoteFundPubkey: FfiConverterArrayBuffer.read(from),
        fundAmount: FfiConverterUInt64.read(from),
        maxWitnessLen: FfiConverterUInt32.read(from),
        inputSerialId: FfiConverterUInt64.read(from),
        contractId: FfiConverterArrayBuffer.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterTypeTransaction.write(value.fundTx, into);
      FfiConverterUInt32.write(value.fundVout, into);
      FfiConverterArrayBuffer.write(value.localFundPubkey, into);
      FfiConverterArrayBuffer.write(value.remoteFundPubkey, into);
      FfiConverterUInt64.write(value.fundAmount, into);
      FfiConverterUInt32.write(value.maxWitnessLen, into);
      FfiConverterUInt64.write(value.inputSerialId, into);
      FfiConverterArrayBuffer.write(value.contractId, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterTypeTransaction.allocationSize(value.fundTx) +
        FfiConverterUInt32.allocationSize(value.fundVout) +
        FfiConverterArrayBuffer.allocationSize(value.localFundPubkey) +
        FfiConverterArrayBuffer.allocationSize(value.remoteFundPubkey) +
        FfiConverterUInt64.allocationSize(value.fundAmount) +
        FfiConverterUInt32.allocationSize(value.maxWitnessLen) +
        FfiConverterUInt64.allocationSize(value.inputSerialId) +
        FfiConverterArrayBuffer.allocationSize(value.contractId)
      );
    }
  }
  return new FFIConverter();
})();

export type DlcTransactions = {
  fund: Transaction;
  cets: Array<Transaction>;
  refund: Transaction;
  fundingScriptPubkey: ArrayBuffer;
};

/**
 * Generated factory for {@link DlcTransactions} record objects.
 */
export const DlcTransactions = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<DlcTransactions, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<DlcTransactions>,
  });
})();

const FfiConverterTypeDlcTransactions = (() => {
  type TypeName = DlcTransactions;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        fund: FfiConverterTypeTransaction.read(from),
        cets: FfiConverterSequenceTypeTransaction.read(from),
        refund: FfiConverterTypeTransaction.read(from),
        fundingScriptPubkey: FfiConverterArrayBuffer.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterTypeTransaction.write(value.fund, into);
      FfiConverterSequenceTypeTransaction.write(value.cets, into);
      FfiConverterTypeTransaction.write(value.refund, into);
      FfiConverterArrayBuffer.write(value.fundingScriptPubkey, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterTypeTransaction.allocationSize(value.fund) +
        FfiConverterSequenceTypeTransaction.allocationSize(value.cets) +
        FfiConverterTypeTransaction.allocationSize(value.refund) +
        FfiConverterArrayBuffer.allocationSize(value.fundingScriptPubkey)
      );
    }
  }
  return new FFIConverter();
})();

export type OracleInfo = {
  publicKey: ArrayBuffer;
  nonces: Array<ArrayBuffer>;
};

/**
 * Generated factory for {@link OracleInfo} record objects.
 */
export const OracleInfo = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<OracleInfo, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<OracleInfo>,
  });
})();

const FfiConverterTypeOracleInfo = (() => {
  type TypeName = OracleInfo;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        publicKey: FfiConverterArrayBuffer.read(from),
        nonces: FfiConverterSequenceBytes.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterArrayBuffer.write(value.publicKey, into);
      FfiConverterSequenceBytes.write(value.nonces, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterArrayBuffer.allocationSize(value.publicKey) +
        FfiConverterSequenceBytes.allocationSize(value.nonces)
      );
    }
  }
  return new FFIConverter();
})();

export type TxInputInfo = {
  txid: string;
  vout: number;
  scriptSig: ArrayBuffer;
  maxWitnessLength: number;
  serialId: bigint;
};

/**
 * Generated factory for {@link TxInputInfo} record objects.
 */
export const TxInputInfo = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<TxInputInfo, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<TxInputInfo>,
  });
})();

const FfiConverterTypeTxInputInfo = (() => {
  type TypeName = TxInputInfo;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        txid: FfiConverterString.read(from),
        vout: FfiConverterUInt32.read(from),
        scriptSig: FfiConverterArrayBuffer.read(from),
        maxWitnessLength: FfiConverterUInt32.read(from),
        serialId: FfiConverterUInt64.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterString.write(value.txid, into);
      FfiConverterUInt32.write(value.vout, into);
      FfiConverterArrayBuffer.write(value.scriptSig, into);
      FfiConverterUInt32.write(value.maxWitnessLength, into);
      FfiConverterUInt64.write(value.serialId, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterString.allocationSize(value.txid) +
        FfiConverterUInt32.allocationSize(value.vout) +
        FfiConverterArrayBuffer.allocationSize(value.scriptSig) +
        FfiConverterUInt32.allocationSize(value.maxWitnessLength) +
        FfiConverterUInt64.allocationSize(value.serialId)
      );
    }
  }
  return new FFIConverter();
})();

export type PartyParams = {
  fundPubkey: ArrayBuffer;
  changeScriptPubkey: ArrayBuffer;
  changeSerialId: bigint;
  payoutScriptPubkey: ArrayBuffer;
  payoutSerialId: bigint;
  inputs: Array<TxInputInfo>;
  inputAmount: bigint;
  collateral: bigint;
  dlcInputs: Array<DlcInputInfo>;
};

/**
 * Generated factory for {@link PartyParams} record objects.
 */
export const PartyParams = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<PartyParams, ReturnType<typeof defaults>>(
      defaults
    );
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<PartyParams>,
    changeOutputAndFees(
      self_: PartyParams,
      feeRate: bigint
    ): ChangeOutputAndFees {
      return ((__rb: Uint8Array) => {
        try {
          return FfiConverterTypeChangeOutputAndFees.lift(__rb);
        } finally {
          nativeModule().rustbuffer_free(__rb);
        }
      })(
        uniffiCaller.rustCallWithError(
          /*liftError:*/ FfiConverterTypeDLCError.lift.bind(
            FfiConverterTypeDLCError
          ),
          /*caller:*/ (callStatus) => {
            return nativeModule().ubrn_uniffi_ddk_ffi_fn_method_partyparams_change_output_and_fees(
              FfiConverterTypePartyParams.lower(
                self_,
                nativeModule().rustbuffer_alloc
              ),
              FfiConverterUInt64.lower(
                feeRate,
                nativeModule().rustbuffer_alloc
              ),
              callStatus
            );
          },
          /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString)
        )
      );
    },
  });
})();

const FfiConverterTypePartyParams = (() => {
  type TypeName = PartyParams;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        fundPubkey: FfiConverterArrayBuffer.read(from),
        changeScriptPubkey: FfiConverterArrayBuffer.read(from),
        changeSerialId: FfiConverterUInt64.read(from),
        payoutScriptPubkey: FfiConverterArrayBuffer.read(from),
        payoutSerialId: FfiConverterUInt64.read(from),
        inputs: FfiConverterSequenceTypeTxInputInfo.read(from),
        inputAmount: FfiConverterUInt64.read(from),
        collateral: FfiConverterUInt64.read(from),
        dlcInputs: FfiConverterSequenceTypeDlcInputInfo.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterArrayBuffer.write(value.fundPubkey, into);
      FfiConverterArrayBuffer.write(value.changeScriptPubkey, into);
      FfiConverterUInt64.write(value.changeSerialId, into);
      FfiConverterArrayBuffer.write(value.payoutScriptPubkey, into);
      FfiConverterUInt64.write(value.payoutSerialId, into);
      FfiConverterSequenceTypeTxInputInfo.write(value.inputs, into);
      FfiConverterUInt64.write(value.inputAmount, into);
      FfiConverterUInt64.write(value.collateral, into);
      FfiConverterSequenceTypeDlcInputInfo.write(value.dlcInputs, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterArrayBuffer.allocationSize(value.fundPubkey) +
        FfiConverterArrayBuffer.allocationSize(value.changeScriptPubkey) +
        FfiConverterUInt64.allocationSize(value.changeSerialId) +
        FfiConverterArrayBuffer.allocationSize(value.payoutScriptPubkey) +
        FfiConverterUInt64.allocationSize(value.payoutSerialId) +
        FfiConverterSequenceTypeTxInputInfo.allocationSize(value.inputs) +
        FfiConverterUInt64.allocationSize(value.inputAmount) +
        FfiConverterUInt64.allocationSize(value.collateral) +
        FfiConverterSequenceTypeDlcInputInfo.allocationSize(value.dlcInputs)
      );
    }
  }
  return new FFIConverter();
})();

export type Payout = {
  offer: bigint;
  accept: bigint;
};

/**
 * Generated factory for {@link Payout} record objects.
 */
export const Payout = (() => {
  const defaults = () => ({});
  const create = (() => {
    return uniffiCreateRecord<Payout, ReturnType<typeof defaults>>(defaults);
  })();
  return Object.freeze({
    create,
    new: create,
    defaults: () => Object.freeze(defaults()) as Partial<Payout>,
  });
})();

const FfiConverterTypePayout = (() => {
  type TypeName = Payout;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      return {
        offer: FfiConverterUInt64.read(from),
        accept: FfiConverterUInt64.read(from),
      };
    }
    write(value: TypeName, into: RustBuffer): void {
      FfiConverterUInt64.write(value.offer, into);
      FfiConverterUInt64.write(value.accept, into);
    }
    allocationSize(value: TypeName): number {
      return (
        FfiConverterUInt64.allocationSize(value.offer) +
        FfiConverterUInt64.allocationSize(value.accept)
      );
    }
  }
  return new FFIConverter();
})();

export enum ExtendedKey {
  InvalidMnemonic,
  InvalidXpriv,
  InvalidXpub,
  InvalidDerivationPath,
}

const FfiConverterTypeExtendedKey = (() => {
  const ordinalConverter = FfiConverterInt32;
  type TypeName = ExtendedKey;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      switch (ordinalConverter.read(from)) {
        case 1:
          return ExtendedKey.InvalidMnemonic;
        case 2:
          return ExtendedKey.InvalidXpriv;
        case 3:
          return ExtendedKey.InvalidXpub;
        case 4:
          return ExtendedKey.InvalidDerivationPath;
        default:
          throw new UniffiInternalError.UnexpectedEnumCase();
      }
    }
    write(value: TypeName, into: RustBuffer): void {
      switch (value) {
        case ExtendedKey.InvalidMnemonic:
          return ordinalConverter.write(1, into);
        case ExtendedKey.InvalidXpriv:
          return ordinalConverter.write(2, into);
        case ExtendedKey.InvalidXpub:
          return ordinalConverter.write(3, into);
        case ExtendedKey.InvalidDerivationPath:
          return ordinalConverter.write(4, into);
      }
    }
    allocationSize(value: TypeName): number {
      return ordinalConverter.allocationSize(0);
    }
  }
  return new FFIConverter();
})();

// Error type: DlcError
export enum DlcError_Tags {
  InvalidSignature = 'InvalidSignature',
  InvalidPublicKey = 'InvalidPublicKey',
  InvalidTransaction = 'InvalidTransaction',
  InsufficientFunds = 'InsufficientFunds',
  InvalidArgument = 'InvalidArgument',
  SerializationError = 'SerializationError',
  Secp256k1Error = 'Secp256k1Error',
  MiniscriptError = 'MiniscriptError',
  InvalidNetwork = 'InvalidNetwork',
  KeyError = 'KeyError',
}
export const DlcError = (() => {
  type InvalidSignature__interface = {
    tag: DlcError_Tags.InvalidSignature;
  };
  class InvalidSignature_
    extends UniffiError
    implements InvalidSignature__interface
  {
    /**
     * @private
     * This field is private and should not be used, use `tag` instead.
     */
    readonly [uniffiTypeNameSymbol] = 'DlcError';
    readonly tag = DlcError_Tags.InvalidSignature;
    constructor() {
      super('DlcError', 'InvalidSignature');
    }

    static new(): InvalidSignature_ {
      return new InvalidSignature_();
    }

    static instanceOf(obj: any): obj is InvalidSignature_ {
      return obj.tag === DlcError_Tags.InvalidSignature;
    }
    static hasInner(obj: any): obj is InvalidSignature_ {
      return false;
    }
  }

  type InvalidPublicKey__interface = {
    tag: DlcError_Tags.InvalidPublicKey;
  };
  class InvalidPublicKey_
    extends UniffiError
    implements InvalidPublicKey__interface
  {
    /**
     * @private
     * This field is private and should not be used, use `tag` instead.
     */
    readonly [uniffiTypeNameSymbol] = 'DlcError';
    readonly tag = DlcError_Tags.InvalidPublicKey;
    constructor() {
      super('DlcError', 'InvalidPublicKey');
    }

    static new(): InvalidPublicKey_ {
      return new InvalidPublicKey_();
    }

    static instanceOf(obj: any): obj is InvalidPublicKey_ {
      return obj.tag === DlcError_Tags.InvalidPublicKey;
    }
    static hasInner(obj: any): obj is InvalidPublicKey_ {
      return false;
    }
  }

  type InvalidTransaction__interface = {
    tag: DlcError_Tags.InvalidTransaction;
  };
  class InvalidTransaction_
    extends UniffiError
    implements InvalidTransaction__interface
  {
    /**
     * @private
     * This field is private and should not be used, use `tag` instead.
     */
    readonly [uniffiTypeNameSymbol] = 'DlcError';
    readonly tag = DlcError_Tags.InvalidTransaction;
    constructor() {
      super('DlcError', 'InvalidTransaction');
    }

    static new(): InvalidTransaction_ {
      return new InvalidTransaction_();
    }

    static instanceOf(obj: any): obj is InvalidTransaction_ {
      return obj.tag === DlcError_Tags.InvalidTransaction;
    }
    static hasInner(obj: any): obj is InvalidTransaction_ {
      return false;
    }
  }

  type InsufficientFunds__interface = {
    tag: DlcError_Tags.InsufficientFunds;
  };
  class InsufficientFunds_
    extends UniffiError
    implements InsufficientFunds__interface
  {
    /**
     * @private
     * This field is private and should not be used, use `tag` instead.
     */
    readonly [uniffiTypeNameSymbol] = 'DlcError';
    readonly tag = DlcError_Tags.InsufficientFunds;
    constructor() {
      super('DlcError', 'InsufficientFunds');
    }

    static new(): InsufficientFunds_ {
      return new InsufficientFunds_();
    }

    static instanceOf(obj: any): obj is InsufficientFunds_ {
      return obj.tag === DlcError_Tags.InsufficientFunds;
    }
    static hasInner(obj: any): obj is InsufficientFunds_ {
      return false;
    }
  }

  type InvalidArgument__interface = {
    tag: DlcError_Tags.InvalidArgument;
    inner: Readonly<{ message: string }>;
  };
  class InvalidArgument_
    extends UniffiError
    implements InvalidArgument__interface
  {
    /**
     * @private
     * This field is private and should not be used, use `tag` instead.
     */
    readonly [uniffiTypeNameSymbol] = 'DlcError';
    readonly tag = DlcError_Tags.InvalidArgument;
    readonly inner: Readonly<{ message: string }>;
    constructor(inner: { message: string }) {
      super('DlcError', 'InvalidArgument');

      this.inner = Object.freeze(inner);
    }
    static new(inner: { message: string }): InvalidArgument_ {
      return new InvalidArgument_(inner);
    }

    static instanceOf(obj: any): obj is InvalidArgument_ {
      return obj.tag === DlcError_Tags.InvalidArgument;
    }
    static hasInner(obj: any): obj is InvalidArgument_ {
      return InvalidArgument_.instanceOf(obj);
    }

    static getInner(obj: InvalidArgument_): Readonly<{ message: string }> {
      return obj.inner;
    }
  }

  type SerializationError__interface = {
    tag: DlcError_Tags.SerializationError;
  };
  class SerializationError_
    extends UniffiError
    implements SerializationError__interface
  {
    /**
     * @private
     * This field is private and should not be used, use `tag` instead.
     */
    readonly [uniffiTypeNameSymbol] = 'DlcError';
    readonly tag = DlcError_Tags.SerializationError;
    constructor() {
      super('DlcError', 'SerializationError');
    }

    static new(): SerializationError_ {
      return new SerializationError_();
    }

    static instanceOf(obj: any): obj is SerializationError_ {
      return obj.tag === DlcError_Tags.SerializationError;
    }
    static hasInner(obj: any): obj is SerializationError_ {
      return false;
    }
  }

  type Secp256k1Error__interface = {
    tag: DlcError_Tags.Secp256k1Error;
    inner: Readonly<{ message: string }>;
  };
  class Secp256k1Error_
    extends UniffiError
    implements Secp256k1Error__interface
  {
    /**
     * @private
     * This field is private and should not be used, use `tag` instead.
     */
    readonly [uniffiTypeNameSymbol] = 'DlcError';
    readonly tag = DlcError_Tags.Secp256k1Error;
    readonly inner: Readonly<{ message: string }>;
    constructor(inner: { message: string }) {
      super('DlcError', 'Secp256k1Error');

      this.inner = Object.freeze(inner);
    }
    static new(inner: { message: string }): Secp256k1Error_ {
      return new Secp256k1Error_(inner);
    }

    static instanceOf(obj: any): obj is Secp256k1Error_ {
      return obj.tag === DlcError_Tags.Secp256k1Error;
    }
    static hasInner(obj: any): obj is Secp256k1Error_ {
      return Secp256k1Error_.instanceOf(obj);
    }

    static getInner(obj: Secp256k1Error_): Readonly<{ message: string }> {
      return obj.inner;
    }
  }

  type MiniscriptError__interface = {
    tag: DlcError_Tags.MiniscriptError;
  };
  class MiniscriptError_
    extends UniffiError
    implements MiniscriptError__interface
  {
    /**
     * @private
     * This field is private and should not be used, use `tag` instead.
     */
    readonly [uniffiTypeNameSymbol] = 'DlcError';
    readonly tag = DlcError_Tags.MiniscriptError;
    constructor() {
      super('DlcError', 'MiniscriptError');
    }

    static new(): MiniscriptError_ {
      return new MiniscriptError_();
    }

    static instanceOf(obj: any): obj is MiniscriptError_ {
      return obj.tag === DlcError_Tags.MiniscriptError;
    }
    static hasInner(obj: any): obj is MiniscriptError_ {
      return false;
    }
  }

  type InvalidNetwork__interface = {
    tag: DlcError_Tags.InvalidNetwork;
  };
  class InvalidNetwork_
    extends UniffiError
    implements InvalidNetwork__interface
  {
    /**
     * @private
     * This field is private and should not be used, use `tag` instead.
     */
    readonly [uniffiTypeNameSymbol] = 'DlcError';
    readonly tag = DlcError_Tags.InvalidNetwork;
    constructor() {
      super('DlcError', 'InvalidNetwork');
    }

    static new(): InvalidNetwork_ {
      return new InvalidNetwork_();
    }

    static instanceOf(obj: any): obj is InvalidNetwork_ {
      return obj.tag === DlcError_Tags.InvalidNetwork;
    }
    static hasInner(obj: any): obj is InvalidNetwork_ {
      return false;
    }
  }

  type KeyError__interface = {
    tag: DlcError_Tags.KeyError;
    inner: Readonly<{ key: ExtendedKey }>;
  };
  class KeyError_ extends UniffiError implements KeyError__interface {
    /**
     * @private
     * This field is private and should not be used, use `tag` instead.
     */
    readonly [uniffiTypeNameSymbol] = 'DlcError';
    readonly tag = DlcError_Tags.KeyError;
    readonly inner: Readonly<{ key: ExtendedKey }>;
    constructor(inner: { key: ExtendedKey }) {
      super('DlcError', 'KeyError');

      this.inner = Object.freeze(inner);
    }
    static new(inner: { key: ExtendedKey }): KeyError_ {
      return new KeyError_(inner);
    }

    static instanceOf(obj: any): obj is KeyError_ {
      return obj.tag === DlcError_Tags.KeyError;
    }
    static hasInner(obj: any): obj is KeyError_ {
      return KeyError_.instanceOf(obj);
    }

    static getInner(obj: KeyError_): Readonly<{ key: ExtendedKey }> {
      return obj.inner;
    }
  }

  function instanceOf(obj: any): obj is DlcError {
    return obj[uniffiTypeNameSymbol] === 'DlcError';
  }

  return Object.freeze({
    instanceOf,
    InvalidSignature: InvalidSignature_,
    InvalidPublicKey: InvalidPublicKey_,
    InvalidTransaction: InvalidTransaction_,
    InsufficientFunds: InsufficientFunds_,
    InvalidArgument: InvalidArgument_,
    SerializationError: SerializationError_,
    Secp256k1Error: Secp256k1Error_,
    MiniscriptError: MiniscriptError_,
    InvalidNetwork: InvalidNetwork_,
    KeyError: KeyError_,
  });
})();
export type DlcError = InstanceType<
  (typeof DlcError)[
    | 'InvalidSignature'
    | 'InvalidPublicKey'
    | 'InvalidTransaction'
    | 'InsufficientFunds'
    | 'InvalidArgument'
    | 'SerializationError'
    | 'Secp256k1Error'
    | 'MiniscriptError'
    | 'InvalidNetwork'
    | 'KeyError']
>;

// FfiConverter for enum DlcError
const FfiConverterTypeDLCError = (() => {
  const ordinalConverter = FfiConverterInt32;
  type TypeName = DlcError;
  class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
    read(from: RustBuffer): TypeName {
      switch (ordinalConverter.read(from)) {
        case 1:
          return new DlcError.InvalidSignature();
        case 2:
          return new DlcError.InvalidPublicKey();
        case 3:
          return new DlcError.InvalidTransaction();
        case 4:
          return new DlcError.InsufficientFunds();
        case 5:
          return new DlcError.InvalidArgument({
            message: FfiConverterString.read(from),
          });
        case 6:
          return new DlcError.SerializationError();
        case 7:
          return new DlcError.Secp256k1Error({
            message: FfiConverterString.read(from),
          });
        case 8:
          return new DlcError.MiniscriptError();
        case 9:
          return new DlcError.InvalidNetwork();
        case 10:
          return new DlcError.KeyError({
            key: FfiConverterTypeExtendedKey.read(from),
          });
        default:
          throw new UniffiInternalError.UnexpectedEnumCase();
      }
    }
    write(value: TypeName, into: RustBuffer): void {
      switch (value.tag) {
        case DlcError_Tags.InvalidSignature: {
          ordinalConverter.write(1, into);
          return;
        }
        case DlcError_Tags.InvalidPublicKey: {
          ordinalConverter.write(2, into);
          return;
        }
        case DlcError_Tags.InvalidTransaction: {
          ordinalConverter.write(3, into);
          return;
        }
        case DlcError_Tags.InsufficientFunds: {
          ordinalConverter.write(4, into);
          return;
        }
        case DlcError_Tags.InvalidArgument: {
          ordinalConverter.write(5, into);
          const inner = value.inner;
          FfiConverterString.write(inner.message, into);
          return;
        }
        case DlcError_Tags.SerializationError: {
          ordinalConverter.write(6, into);
          return;
        }
        case DlcError_Tags.Secp256k1Error: {
          ordinalConverter.write(7, into);
          const inner = value.inner;
          FfiConverterString.write(inner.message, into);
          return;
        }
        case DlcError_Tags.MiniscriptError: {
          ordinalConverter.write(8, into);
          return;
        }
        case DlcError_Tags.InvalidNetwork: {
          ordinalConverter.write(9, into);
          return;
        }
        case DlcError_Tags.KeyError: {
          ordinalConverter.write(10, into);
          const inner = value.inner;
          FfiConverterTypeExtendedKey.write(inner.key, into);
          return;
        }
        default:
          // Throwing from here means that DlcError_Tags hasn't matched an ordinal.
          throw new UniffiInternalError.UnexpectedEnumCase();
      }
    }
    allocationSize(value: TypeName): number {
      switch (value.tag) {
        case DlcError_Tags.InvalidSignature: {
          return ordinalConverter.allocationSize(1);
        }
        case DlcError_Tags.InvalidPublicKey: {
          return ordinalConverter.allocationSize(2);
        }
        case DlcError_Tags.InvalidTransaction: {
          return ordinalConverter.allocationSize(3);
        }
        case DlcError_Tags.InsufficientFunds: {
          return ordinalConverter.allocationSize(4);
        }
        case DlcError_Tags.InvalidArgument: {
          const inner = value.inner;
          let size = ordinalConverter.allocationSize(5);
          size += FfiConverterString.allocationSize(inner.message);
          return size;
        }
        case DlcError_Tags.SerializationError: {
          return ordinalConverter.allocationSize(6);
        }
        case DlcError_Tags.Secp256k1Error: {
          const inner = value.inner;
          let size = ordinalConverter.allocationSize(7);
          size += FfiConverterString.allocationSize(inner.message);
          return size;
        }
        case DlcError_Tags.MiniscriptError: {
          return ordinalConverter.allocationSize(8);
        }
        case DlcError_Tags.InvalidNetwork: {
          return ordinalConverter.allocationSize(9);
        }
        case DlcError_Tags.KeyError: {
          const inner = value.inner;
          let size = ordinalConverter.allocationSize(10);
          size += FfiConverterTypeExtendedKey.allocationSize(inner.key);
          return size;
        }
        default:
          throw new UniffiInternalError.UnexpectedEnumCase();
      }
    }
  }
  return new FFIConverter();
})();

// FfiConverter for Array<ArrayBuffer>
const FfiConverterSequenceBytes = new FfiConverterArray(
  FfiConverterArrayBuffer
);

// FfiConverter for Array<TxInput>
const FfiConverterSequenceTypeTxInput = new FfiConverterArray(
  FfiConverterTypeTxInput
);

// FfiConverter for Array<TxOutput>
const FfiConverterSequenceTypeTxOutput = new FfiConverterArray(
  FfiConverterTypeTxOutput
);

// FfiConverter for Array<Transaction>
const FfiConverterSequenceTypeTransaction = new FfiConverterArray(
  FfiConverterTypeTransaction
);

// FfiConverter for Array<TxInputInfo>
const FfiConverterSequenceTypeTxInputInfo = new FfiConverterArray(
  FfiConverterTypeTxInputInfo
);

// FfiConverter for Array<DlcInputInfo>
const FfiConverterSequenceTypeDlcInputInfo = new FfiConverterArray(
  FfiConverterTypeDlcInputInfo
);

// FfiConverter for string | undefined
const FfiConverterOptionalString = new FfiConverterOptional(FfiConverterString);

// FfiConverter for Array<OracleInfo>
const FfiConverterSequenceTypeOracleInfo = new FfiConverterArray(
  FfiConverterTypeOracleInfo
);

// FfiConverter for Array<Array<ArrayBuffer>>
const FfiConverterSequenceSequenceBytes = new FfiConverterArray(
  FfiConverterSequenceBytes
);

// FfiConverter for Array<Array<Array<ArrayBuffer>>>
const FfiConverterSequenceSequenceSequenceBytes = new FfiConverterArray(
  FfiConverterSequenceSequenceBytes
);

// FfiConverter for Array<AdaptorSignature>
const FfiConverterSequenceTypeAdaptorSignature = new FfiConverterArray(
  FfiConverterTypeAdaptorSignature
);

// FfiConverter for Array<Payout>
const FfiConverterSequenceTypePayout = new FfiConverterArray(
  FfiConverterTypePayout
);

/**
 * This should be called before anything else.
 *
 * It is likely that this is being done for you by the library's `index.ts`.
 *
 * It checks versions of uniffi between when the Rust scaffolding was generated
 * and when the bindings were generated.
 *
 * It also initializes the machinery to enable Rust to talk back to Javascript.
 */
function uniffiEnsureInitialized() {
  // Get the bindings contract version from our ComponentInterface
  const bindingsContractVersion = 30;
  // Get the scaffolding contract version by calling the into the dylib
  const scaffoldingContractVersion =
    nativeModule().ubrn_ffi_ddk_ffi_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new UniffiInternalError.ContractVersionMismatch(
      scaffoldingContractVersion,
      bindingsContractVersion
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_convert_mnemonic_to_seed() !==
    29793
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_convert_mnemonic_to_seed'
    );
  }
  if (nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_cet() !== 62951) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_cet'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_cet_adaptor_points_from_oracle_info() !==
    14977
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_cet_adaptor_points_from_oracle_info'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_cet_adaptor_sigs_from_oracle_info() !==
    5605
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_cet_adaptor_sigs_from_oracle_info'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_cet_adaptor_sigs_from_points() !==
    39452
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_cet_adaptor_sigs_from_points'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_cets() !== 22051
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_cets'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_dlc_transactions() !==
    47767
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_dlc_transactions'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_extkey_from_parent_path() !==
    23090
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_extkey_from_parent_path'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_extkey_from_seed() !==
    45469
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_extkey_from_seed'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_fund_tx_locking_script() !==
    37235
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_fund_tx_locking_script'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_refund_transaction() !==
    40230
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_refund_transaction'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_spliced_dlc_transactions() !==
    44189
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_spliced_dlc_transactions'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_create_xpriv_from_parent_path() !==
    7895
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_create_xpriv_from_parent_path'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_extract_ecdsa_signature_from_oracle_signatures() !==
    4868
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_extract_ecdsa_signature_from_oracle_signatures'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_get_pubkey_from_extkey() !==
    18050
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_get_pubkey_from_extkey'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_get_total_input_vsize() !==
    2998
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_get_total_input_vsize'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_get_xpub_from_xpriv() !==
    8843
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_get_xpub_from_xpriv'
    );
  }
  if (
    nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_verify_cet_adaptor_sigs_from_oracle_info() !==
    32235
  ) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_verify_cet_adaptor_sigs_from_oracle_info'
    );
  }
  if (nativeModule().ubrn_uniffi_ddk_ffi_checksum_func_version() !== 2994) {
    throw new UniffiInternalError.ApiChecksumMismatch(
      'uniffi_ddk_ffi_checksum_func_version'
    );
  }
}

export default Object.freeze({
  initialize: uniffiEnsureInitialized,
  converters: {
    FfiConverterTypeAdaptorSignature,
    FfiConverterTypeCetAdaptorSignatureDebugInfo,
    FfiConverterTypeChangeOutputAndFees,
    FfiConverterTypeDLCError,
    FfiConverterTypeDlcInputInfo,
    FfiConverterTypeDlcTransactions,
    FfiConverterTypeExtendedKey,
    FfiConverterTypeOracleInfo,
    FfiConverterTypePartyParams,
    FfiConverterTypePayout,
    FfiConverterTypeTransaction,
    FfiConverterTypeTxInput,
    FfiConverterTypeTxInputInfo,
    FfiConverterTypeTxOutput,
  },
});
