name: ddk-ffi CI

on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: ddk-ffi/target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo Check
        run: |
          cd ddk-ffi
          cargo check --all-features

      - name: Format Check
        run: |
          cd ddk-ffi
          cargo fmt -- --check

      - name: Clippy Check
        run: |
          cd ddk-ffi
          cargo clippy --all-features -- -D warnings

      - name: Run Tests
        run: |
          cd ddk-ffi
          cargo test --all-features
