name: Bindings Feature Parity

on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]
jobs:
  feature-parity:
    name: Feature Parity Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.17"

      - name: Check Feature Parity
        run: |
          cd ddk-ts
          node scripts/verify-parity.cjs

      - name: Verify Types
        run: |
          cd ddk-ts
          node scripts/verify-types.cjs
